Section Cassandra
DCC-org/documents pull request #122
Opened 2017-01-30 20:36 UTC by StoneCat

2017-02-18 11:36 UTC, Marcellii requested changes
Sind ein paar Kleinigkeiten nichts großes MR

2017-02-18 11:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +Managment der Arbeitsauslastung auf dem Server. Dazu nutzt die Software ein
Management

2017-02-18 11:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +Nodes ermöglicht. Wenn auf einen einzelnen Node Dateninformationen erstellt,
wenn auf einem

2017-02-18 11:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +modifiziert oder entfernt werden, erhält ein weitere Node in der Infrastruktur
weiterer

2017-02-18 11:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +diese Information und baut gleichzeitig ein Replikation des Objektes.
eine?

2017-02-18 11:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +``Owns'', von 50 Prozentpunkte besitzen. Dies bedeutet, dass jeder Node jeweils
Prozentpunkte

2017-02-18 11:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +die Hälfte der Dateninformationen bereitstellt, jedoch auch die zugehörige Häfte
Hälfte

2017-02-18 11:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +ausfallen, könnte der jeweils andere autoamtisch einen Dateneigentum von 100
automatisch

2017-02-18 12:05 UTC, StoneCat commented
Latex build not tested

2017-02-18 12:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\lstinputlisting[language=bash,caption={postgres git clone}]{../listings/cassandra-status.txt}
bitte die caption anpassen. das steht dann über/unter dem text.

2017-02-18 12:10 UTC, bastelfreak commented on thesis-de/content-de.tex
> +den Ausfall von Hardwarekomponenten oder Softwareteilen auf dem System zu
ich denke da fehlt ein komma:
"oder Softwareteilen,"

2017-02-18 12:10 UTC, bastelfreak commented on thesis-de/content-de.tex
> +verhindern. Dazu wird ein Peer-to-Peer Verfahren verwendet, welches die
Peer-to-Peer ins glossar

2017-02-18 12:11 UTC, bastelfreak commented on thesis-de/content-de.tex
> +verhindern. Dazu wird ein Peer-to-Peer Verfahren verwendet, welches die
Client-server prinzip sollte auch mit aufgenomen werden, dies ist das gegenteilige verfahren,

2017-02-18 12:12 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Umfeld wird dies über die von dem Hersteller definierten Protokoll ``gossip''
"wird dies über das"

weil singular, nicht plural

2017-02-18 12:15 UTC, bastelfreak commented on thesis-de/content-de.tex
> +diese Information und baut gleichzeitig eine Replikation des Objektes.
ist das synchron oder asynchron? Wann wird dem client mitgeteilt ob die daten erfolgreich geschrieben wurden? Wenn der erste Node die geschrieben hat (asynchrone replikation) oder wenn ebenfalls der zweite sie geschrieben hat (synchrone replikation)?

2017-02-18 12:17 UTC, bastelfreak commented on listings/cassandra-status.txt
> +UN  127.0.0.1  692.18 MB  256     	50.0%             95659096-97ef-419f-bd82-693f19ad7679  rack2
sollen wir die Host ID etwas kürzen?
z.b. nur 95659096-97ef-419f oder 95659096-..693f19ad7679

die volle länge list leider zu breit und dann wrappt das um und dann ists hässlich :sadface:

2017-02-18 12:20 UTC, bastelfreak commented on thesis-de/content-de.tex
> +weiterarbeiten.
kannst du noch das stichwort Shared-Nothing-Architektur einbauen?
die bedeutet, das alles nodes im cluster den dienst bereitstellen können und nicht zwangsläufig auf andere nodes angewiesen sind, dies is hier ja der fall aufgrund der replika. Ich nutze das wort schon irgendwo weiter oben.

2017-02-18 13:22 UTC, bastelfreak commented on glossary.tex
> +               Internet. Dabei kommunizieren zwei Teilnehmer über eine direkte
"zwei oder mehr Teilnehmer"

2017-02-18 13:23 UTC, bastelfreak commented on glossary.tex
> +               Verbindung miteinander, ohne das einer der beiden eine
würde den letzten nebensatz weglassen und sowas wie:
"In einem Peer to Peer Netzwerk sind alle Teilnehmer gleichgestellt, die alternative ist das Client-Server Modell"

schreiben

2017-02-18 13:29 UTC, bastelfreak commented on glossary.tex
> +  description={Eine Partitione definiert einen logischen Bereich der im
das passt nicht ganz zum kontext der datenbanken.

Partitionierung im allgemeinen beschreibt das einteilen vorhandener ressourcen in blöcke.

Am bekanntesten ist dies bei Festplatten. hier teilt man vorhandenen speicher in mehrere logische bereiche ein. Bei Datenbanken gibt es ebenfalls partitioning. hier hat man zumeist eine viel zu fette tabelle und irgendeinen tollen identifer, z.b. ein datum. wenn man hier von partitioning spricht dann erstellt man mehrere versteckte tabellen, z.b. eine pro tag oder pro stunde. nach aussen hin ist erstmal nur die eine große sichtbar, die setzt sich aber aus den anderen zusammen. wenn man dann selects draufprügelt mit WHERE clause die nach datum sucht dann weis das DBMS in welcher untertabelle/partition es schauen muss, geht somit wesentlich schneller weil nicht der index einer mega tabelle gelesen werden muss. oder noch schlimmer ein sequential scan

2017-02-18 13:29 UTC, bastelfreak commented on glossary.tex
> +  description={Eine Partitione definiert einen logischen Bereich der im
beispiel: https://www.postgresql.org/docs/9.6/static/ddl-partitioning.html

2017-02-18 14:38 UTC, StoneCat commented
@bastelfreak please write glossary entry 'Partitionen'

2017-02-18 14:40 UTC, bastelfreak commented on glossary.tex
> +  description={In einer Ringtopologie ist jede Station mit ihrer Nachbarstation
plural oder, Nachbarstationen?
Bei einem Ring hat jeder Teilnehmer zwei direkte Partner.

2017-02-18 14:41 UTC, bastelfreak commented on glossary.tex
> +  name=Peer-to-Peer,
Peer-to-Peer ist doppelt drinn?

2017-02-18 14:41 UTC, bastelfreak commented on glossary.tex
> +               Netzwerk bzw. Internet. Dabei kommuniziert ein oder mehrere
"bzw. Internet" streichen.

2017-02-18 14:42 UTC, bastelfreak commented on glossary.tex
> +               Server angewiesen.}
, da er benötigte Dienste im Netzwerk anbietet.

2017-02-18 14:42 UTC, bastelfreak commented on glossary.tex
> +  description={Eine Partitione definiert einen logischen Bereich der im
schreib ich später ins glossar

2017-02-18 14:42 UTC, Marcellii approved these changes

2017-02-18 14:45 UTC, bastelfreak requested changes
siehe inline kommentare

2017-02-18 14:57 UTC, StoneCat commented on glossary.tex
> +  name=Peer-to-Peer,
Gesoffen? ne...

2017-02-19 13:16 UTC, bastelfreak commented on glossary.tex
> +  name=Peer-to-Peer,
doch, ist doppelt drinn

2017-02-19 13:17 UTC, bastelfreak commented on glossary.tex
> +\newglossaryentry{Partitionen}
Partitionen ist jetzt ebenfalls doppelt

2017-02-19 13:17 UTC, bastelfreak commented on glossary.tex
> +  description={In einer Ringtopologie ist jede Station mit ihrer direkten
mit ihren

2017-02-19 13:21 UTC, bastelfreak commented on thesis-de/content-de.tex
> +weiterarbeiten. Dies ist mit der Shared-Nothing-Architektur zu vergleichen,
letzten satz vielleicht umformulieren ala:
"Dieses Verfahren wird auch  Shared-Nothing-Architektur genannt". Das ist genau das, es ist nicht nur vergleichbar.

2017-02-19 13:21 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Konfiguration eingestellt und eingesetzt werden. Cassandra bietet zudem drei
welche drei modelle sind das? kannst du die ganz grob beschreiben?

2017-02-19 13:25 UTC, bastelfreak commented
in glossary.tex sind teilweise hard tabs drinn, bitte das mal fixen. vim kann das von haus aus mit :retab

2017-02-19 13:27 UTC, bastelfreak commented on glossary.tex
> +  description={Eingabe, Verarbeitung, Ausgabe. Ein Prinzip aus der Datenverarbeitung.
da fehlt die klammer am ende

2017-02-25 15:10 UTC, bastelfreak commented on glossary.tex
> +               Internet. Dabei kommunizieren zwei Teilnehmer über eine direkte
fixed

2017-02-25 15:10 UTC, bastelfreak commented on glossary.tex
> +               Verbindung miteinander, ohne das einer der beiden eine
fixed

2017-02-25 15:11 UTC, bastelfreak commented on glossary.tex
> +  description={In einer Ringtopologie ist jede Station mit ihrer Nachbarstation
fixed

2017-02-25 15:11 UTC, bastelfreak commented on glossary.tex
> +  description={Eine Partitione definiert einen logischen Bereich der im
hat nikolai angepasst

2017-02-25 15:14 UTC, bastelfreak commented on glossary.tex
> +  name=Peer-to-Peer,
fixed

2017-02-25 15:14 UTC, bastelfreak commented on glossary.tex
> +  description={Eingabe, Verarbeitung, Ausgabe. Ein Prinzip aus der Datenverarbeitung.
fixed. baut jetzt auch...

2017-02-25 15:14 UTC, bastelfreak commented on glossary.tex
> +\newglossaryentry{Partitionen}
fixed

2017-02-25 15:15 UTC, bastelfreak commented on glossary.tex
> +  description={In einer Ringtopologie ist jede Station mit ihrer direkten
fixed

2017-02-25 15:35 UTC, bastelfreak approved these changes

2017-02-25 15:35 UTC, merged