[WIP]Fix the section which was requested by David
DCC-org/documents pull request #123
Opened 2017-02-01 19:53 UTC by Marcellii

I have deleted the redundant list from the UI Software

2017-02-04 10:50 UTC, StoneCat requested changes
Hier muss nochmal dran gearbeitet werden. Gerne auch in einem gemeinsamen Call.

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
> +Software, ist aufgefallen, dass es sich hierbei nicht direkt um eine
hinter Software kein Komma

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
>  einer Weboberfläche, nämlich das Drag \& Drop, von einzelnen Graphen.
"nämlich das Drag \& Drop, von einzelnen Graphen" würde ich hinter "eine Funktion" setzen und nicht ans Ende des Textes

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
> +Zusammenfassung:
Leerzeichen weg

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
> +ab. Zusätzlich ist aufgefallen, das Zabbix-Frontend maximal nur mit einer
Hier past plural und singular nicht ganz zusammen -> klingt komisch. 
"Frontend" singular - "das...xy...kommunizieren" plural
Versuch ein anderes Wort für FrontEnd zu finden

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
> +Datenbank gleichzeitig kommunizieren und verwenden kann. Anders als bei
verwenden kann -> du meinst wohl "verwendet werden kann".

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
> +Grafana, wo mehrere Datenbanken eingebunden werden können, welche über die
, wo -> ist kein richtiges Deutsch hat meine Lehrerin damals immer gesagt -> niemals einen Nebensatz mit "wo" beginnen

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Dashboards beim neuladen der Seite, oder aber auch ein Wert z.B. der CPU
das Neuladen??

2017-02-04 10:50 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Datenhaltungssystem abgerufen werden können. Ebenso, sollte der Aufbau des
Hier sollte meiner Meinung nach darauf geachtet werden, dass die Anfragen nicht zu häufig stattfinden und somit auch nicht das Datenhaltungssystem auf die Knie zwingt -> das hat schon genug zu tun mit der Datenextraktion und Transformation. 

Was wäre denn, wenn aufeinmal 500 Call Center Agents deine Weboberfläche angezeigt bekommen. Würde dann die Datenbank sekündlich mit komplexen Anfragen zugeballert werden? bisschen uncool oder? Vielleicht ist noch der Punkt "ein minimaler Aktualisierungszyklus muss vom Administrator vorgegeben werden können, um die Last bei dem Datenhaltungssystem zu kontrollieren" 
Gleichzeitig kommt die Frage auf, wie weit soetwas im Cache zwischengespeichert werden kann... Die Dashboards bei mir auf der Arbeit greifen auf 9 millionen Datensätze zu und sind sozusagen bei fast jedem Mitarbeiter auf dem Rechner abrufbar, da ist ein Cacheing zwingend erforderlich!

2017-02-04 13:38 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Datenhaltungssystem abgerufen werden können. Ebenso, sollte der Aufbau des
jap habe ich angepasst danke dafür

2017-02-04 13:39 UTC, Marcellii commented on thesis-de/content-de.tex
> +Grafana, wo mehrere Datenbanken eingebunden werden können, welche über die
angepasst

2017-02-04 13:39 UTC, Marcellii commented on thesis-de/content-de.tex
> +Datenbank gleichzeitig kommunizieren und verwenden kann. Anders als bei
richtig

2017-02-04 13:39 UTC, Marcellii commented on thesis-de/content-de.tex
> +ab. Zusätzlich ist aufgefallen, das Zabbix-Frontend maximal nur mit einer
weiß nicht genau was du hier mit Singular und Plural meinst Zabbix-Frontend ist ein Name, bzw. so heißt die Komponente

2017-02-04 13:40 UTC, Marcellii commented on thesis-de/content-de.tex
> +Zusammenfassung:
done

2017-02-04 13:40 UTC, Marcellii commented on thesis-de/content-de.tex
>  einer Weboberfläche, nämlich das Drag \& Drop, von einzelnen Graphen.
jap klingt besser danke

2017-02-04 13:40 UTC, Marcellii commented on thesis-de/content-de.tex
> +Software, ist aufgefallen, dass es sich hierbei nicht direkt um eine
done

2017-02-04 13:40 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Dashboards beim neuladen der Seite, oder aber auch ein Wert z.B. der CPU
aktualisieren

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Der wichtigste Aspekt, bei der Performance der Weboberfläche, ist
Der Satz ist viel zu kompliziert. Zum einen sind da zu viele Kommas, zum anderen würde bei der Schreibweise noch weitere Komma fehlen -> ,ist, -> ,dass Werte -> werden, aus. 
Schreib den einfach komplett neu, dann hast du nicht so einen hässlichen Satz...

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +  verwendet werden, um die Auslastung auf dem Datenhaltunssystem so gering wie
Und das ist nicht präzise genug. Wie kommen die Daten in den Zwischenspeicher? Wie lange bleiben die dort? Wann wird entschieden, bzw. woher weiß der Zwischenspeicher, dass seine Informationen nicht mehr aktuell sind?

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Zwieschenspeicher des Dashboards bzw. der Weboberfläche erfolgen. Wie auch die
Zwieschenspeicher falsch geschrieben

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +  das Datenhaltungssystem weitergeleitet werden, sondern müssen aus dem
500 Nutzer haben ein Webdashboard mit 2-8 Graphen. Jeder dieser Graphen verursacht eine einzelne Abfrage an der Datenhaltung, also sind es doch Graphenanzahl * Nutzer = Abfragen...

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +  große Zeitdifferenzen visualisiert und angezeigt werden können. Ebenfalls,
Ebenfalls, -> ich glaube hier kommt kein Komma hin

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +  sollte dem Aufbau des Dashboards bei einer Aktualisierung der Seite, oder aber
Lies den Satz mal laut... Für mich sind hier irgendwelche Worte zusammengewürfelt die keinen Sinn machen?

sollte bei dem Aufbau? 
während der Aktualisierung?
oder bei einer Änderung eines einzelnen Wertes? 
ändert sich massiv direkt????? -> was ist das denn für ein Deutsch? massiv direkt Bruder
zeitlichen -> klein
Unterschied -> groß 

Hast du bei dem Satz gesoffen? :rofl:

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +
Was soll das "+" hier?

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
>  OpenSource Basis auf \gls{GitHub} liegt. Während der Evaluierung von dieser
liegt -> einsehbar/dokumentiert ist

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +Visualisierungssoftware handelt, sondern lediglich eine Funktion, nämlich das
, dem Drag \& Drop -> und dann im Glossar kurz Drag & Drop erläutern -> dann kannst du das nämlich weg lassen

(Ist nur im Vorschlag der mir gerade aufgefallen ist, macht den Satz noch smarter -> ist mir beim ersten Comment nicht aufgefallen sorry)

(Da kommt mir nur immer der Satz aus der Schule in Kopf :D "Wer nämlich sagt ist dämlich")

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +verwendet werden kann. Anders als bei Grafana, welches mit mehreren Datenbanken
Sehr schön! Der Satz klingt jetzt vernünftig :ok:

2017-02-06 13:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +ab. Zusätzlich ist aufgefallen, das Zabbix-Frontend maximal nur mit einer
Jo passt auch mit deinem neuen Satz/Änderungen

2017-02-06 13:57 UTC, StoneCat requested changes
Some More Changes

2017-02-06 19:48 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Der wichtigste Aspekt, bei der Performance der Weboberfläche, ist
also ich würd den Satz bzw. diesen Abschnitt komplett neuschreiben.. überlege mir gerade die Themen die dort hinein kommen

2017-02-07 19:24 UTC, Marcellii commented on thesis-de/content-de.tex
> +  verwendet werden, um die Auslastung auf dem Datenhaltunssystem so gering wie
schreibe ich neu

2017-02-07 19:24 UTC, Marcellii commented on thesis-de/content-de.tex
> +  das Datenhaltungssystem weitergeleitet werden, sondern müssen aus dem
schreibe ich neu

2017-02-07 19:24 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Zwieschenspeicher des Dashboards bzw. der Weboberfläche erfolgen. Wie auch die
schreibe ich neu

2017-02-07 19:24 UTC, Marcellii commented on thesis-de/content-de.tex
> +  große Zeitdifferenzen visualisiert und angezeigt werden können. Ebenfalls,
schreibe ich neu

2017-02-07 19:25 UTC, Marcellii commented on thesis-de/content-de.tex
> +  sollte dem Aufbau des Dashboards bei einer Aktualisierung der Seite, oder aber
ich glaub schon :D schreibe ich auch neu

2017-02-07 19:26 UTC, Marcellii commented on thesis-de/content-de.tex
> +
irgendwie ist da kein + :D

2017-02-07 19:27 UTC, Marcellii commented on thesis-de/content-de.tex
>  OpenSource Basis auf \gls{GitHub} liegt. Während der Evaluierung von dieser
done

2017-02-07 19:30 UTC, Marcellii commented on thesis-de/content-de.tex
> +verwendet werden kann. Anders als bei Grafana, welches mit mehreren Datenbanken
k

2017-02-07 19:30 UTC, Marcellii commented on thesis-de/content-de.tex
> +Visualisierungssoftware handelt, sondern lediglich eine Funktion, nämlich das
musste mir mal erklären wie du des meinst

2017-02-13 18:27 UTC, StoneCat requested changes

2017-02-13 18:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Ein kurzes Rechenbeispiel soll dies verdeutlichen. 8 unterschiedliche User
8 in Worten

2017-02-13 18:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Fallbeispiel 8 Grapfen, mit unterschiedlichen Werden. Nun sind hier insgesamt
Werden -> Werten

2017-02-13 18:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +  64 Graohen, welche sekündlich eine Abfrage an das Datenhaltungssystem senden
Graohen -> Graphen

2017-02-13 18:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +  sondern auch die Datenerhaltung um Daten abzuspeichern, kann es hier zu
Datenerhaltung -> anders schreiben

2017-02-14 14:13 UTC, ehwat commented on thesis-de/content-de.tex
> +  64 Graohen, welche sekündlich eine Abfrage an das Datenhaltungssystem senden
genauso wie Grapfen ↦ Graphen und Werden ↦ Werten

2017-02-15 19:51 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Ein kurzes Rechenbeispiel soll dies verdeutlichen. 8 unterschiedliche User
done muss die 64 auch in Worte`?

2017-02-15 19:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Fallbeispiel 8 Grapfen, mit unterschiedlichen Werden. Nun sind hier insgesamt
done

2017-02-15 19:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +  64 Graohen, welche sekündlich eine Abfrage an das Datenhaltungssystem senden
done

2017-02-15 19:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +  sondern auch die Datenerhaltung um Daten abzuspeichern, kann es hier zu
done

2017-02-17 15:15 UTC, StoneCat approved these changes

2017-02-18 13:53 UTC, bastelfreak commented on thesis-de/content-de.tex
> +
das bedeutet, dass da eine neue leerzeile ist.

2017-02-18 13:53 UTC, bastelfreak commented on glossary.tex
> +              entweder alleine oder im Team an einem Quellcode zusammen arbeiten.
Quellcode durch Softwareprojekte ersetzen.

2017-02-18 13:57 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Bei der Evaluierung der Weboberfläche, sollte zusätzlich zu den bereits
kein komma

2017-02-18 14:00 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Cookies, sowie Cache unterstützen. Der Browser Cache wird jeweils vom Browser
was haben cookies damit zutun?

2017-02-18 14:00 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Algorythmus, dass eine Seite mehrfach aufgerufen worden ist und speichert
Algorithmus

2017-02-18 14:02 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  eine gewisse Zeitspanne vordefinieren kann, in welchem die Graphen neu
in welcher, nicht welchem

2017-02-18 14:04 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Bei der Evaluierung der Weboberfläche, sollte zusätzlich zu den bereits
die einleitung ist redundant. wir sind bereits in der liste der Kriterien, das muss nicht explizit erwähnt werden.

2017-02-18 14:05 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Cookies, sowie Cache unterstützen. Der Browser Cache wird jeweils vom Browser
Browser cache ist, wie der name sagt, Browserseitig. Was hat die webseite damit zutun?

2017-02-18 14:06 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Gridster ist eine von Anmol Koul entwickelte OpenSource Softwarelösung, welche
welche Lizenz hat die software?

2017-02-18 14:06 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Gridster ist eine von Anmol Koul entwickelte OpenSource Softwarelösung, welche
ich dachte es gibt eine kostenpflichtige lizenz?

2017-02-18 14:12 UTC, bastelfreak commented on thesis-de/content-de.tex
> +bereitet diese auf und speichert die zuvor aufbereitete Daten anschließend in
ist wieder redundant, es reicht einmal zu erwähnen, dass daten aufbereitet werden.

2017-02-18 14:15 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Visualisierungssoftware handelt, sondern lediglich eine Funktion, nämlich das
bei der software handelt es sich um eine funktion? kannst du das etwas ausführlicher schreiben?

2017-02-18 14:46 UTC, bastelfreak requested changes
siehe inline kommentare

2017-02-18 14:57 UTC, Marcellii commented on glossary.tex
> +              entweder alleine oder im Team an einem Quellcode zusammen arbeiten.
done

2017-02-18 14:59 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Bei der Evaluierung der Weboberfläche, sollte zusätzlich zu den bereits
hab den Satz gestrichen

2017-02-18 15:00 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Cookies, sowie Cache unterstützen. Der Browser Cache wird jeweils vom Browser
Eigentlich hat die Webseite damit nichts zu tun und coockies schon garnicht

2017-02-18 15:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Algorythmus, dass eine Seite mehrfach aufgerufen worden ist und speichert
hab den Teil rausgestrichen

2017-02-18 15:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +  eine gewisse Zeitspanne vordefinieren kann, in welchem die Graphen neu
done

2017-02-18 15:07 UTC, Marcellii commented on thesis-de/content-de.tex
> +Gridster ist eine von Anmol Koul entwickelte OpenSource Softwarelösung, welche
Gridster-3d ist kostenlos und der Quellcode liegt auf GitHub

2017-02-18 15:09 UTC, Marcellii commented on thesis-de/content-de.tex
> +bereitet diese auf und speichert die zuvor aufbereitete Daten anschließend in
done

2017-02-18 15:12 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Bei der Evaluierung der Weboberfläche, sollte zusätzlich zu den bereits
immernoch komma zu viel

2017-02-18 15:24 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  überlastet wird.  Ein kurzes Rechenbeispiel soll dies verdeutlichen. Acht
Vor "Ein" sind zwei leerzeichen

2017-02-18 15:28 UTC, bastelfreak commented on thesis-de/content-de.tex
> +individuell anpassen zu können, Graphen zu verschieben oder direkt zu löschen.
wenn ich das richtig sehe geht es bei gridster um das verschieben von div containern auf einer html seite.

https://anmolkoul.wordpress.com/2015/07/06/drag-and-drop-visuals-in-your-interactive-dashboard-gridster-d3-js/

die graphen sind da nur zufällig drinn

2017-02-18 15:37 UTC, Marcellii commented on thesis-de/content-de.tex
> +  überlastet wird.  Ein kurzes Rechenbeispiel soll dies verdeutlichen. Acht
done

2017-02-18 15:51 UTC, bastelfreak approved these changes

2017-02-18 16:01 UTC, merged