[WIP}add userstory for ssd story
DCC-org/documents pull request #124
Opened 2017-02-04 10:25 UTC by Marcellii

if the administrator, will see, which ssd will kill

2017-02-04 14:41 UTC, StoneCat requested changes

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +dies für eine schnellere Absicherung der Daten. SSDs haben jedoch, wie auch
schnelleren Datenzugriff

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +HDDs einen Lebenszyklus, der bei SSD schneller erreicht werden kann. Der
im Vergleich zu was?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +ausgegeben werden, welche SSD von welchem Hersteller in der Wahrscheinlichkeit
Die Statistik können wir liefern? Besitzen wir im Projekt eine Datenbank mit allen Metadaten der physischen Kisten? Also Server200112 in Rack212 besitzt CPU von ... RAM von ... SSD von ... ? Ich glaube das haben wir nicht, bzw haben wir noch nie irgendwo definiert,

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Die Ausgabe und Visualisierung in einen Diagramm, ob Balken- oder
in einem

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Die Ausgabe und Visualisierung in einen Diagramm, ob Balken- oder
tausche "ob" mit "vorzugsweise ein"

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  wenn ein kritischer Schreib- oder Lesezyklus erreicht worden ist.
Punkt am Ende? War bei den anderen Aufzählungen nicht

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Auflistung einer Statistik in Form eines Balkendiagramms, über die
Wie gesagt, weiß ich nicht, ob wir die Leistung erbringen können.

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +\mr%
Zu jeder User-Story gehört auch eine Skizze der UI (zumindest kenne ich das so von meinem Alltag im Büro)

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +\\textbf{Name der Story:}\\ Auswertung der CPU Auslastung von jeder Instanz, um Engpässe zu
ich glaube das "von" kann man hier weg lassen

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Die CPUs der heutigen Zeit werden immer schneller und besser, von
Die CPUs der heutigen Zeit werden in der Taktrate und Verarbeitungsgeschwindigkeit der Prozesse immer schneller und besser -> liest sich meiner Meinung nach besser

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +Virtuellen Maschine, werden die CPUs jeweils pro Virtueller Maschine zugewiesen,
Virtuellen -> klein?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +so kann eine Maschine 2 CPU Kerne mit z.B. 2,5 GHz Takrate zugewiesen werden.
Der Satz ist absolut unverständlich. 300 mal das Wort zugewiesen und 400 mal das Wort virtuelle Maschine :-D

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +unterschiedliche CPUs zugewiesen haben. Manchmal kommt es hier vor, das eine VM
hat? haben wird? haben kann?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +zu viel Rechenleistung, bedingt durch ausgeführte Dienste benötigt. Wenn eine
bedingt durch ausgeführte Dienste, {Komma} benötigt

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +unterschiedliche CPUs zugewiesen haben. Manchmal kommt es hier vor, das eine VM
Manchmal kommt es hier vor -> ist keine fachlich Korrekte Aussage und zu ungenau (bitte nicht das wort manchmal verwenden)

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +Virtuellen Instanz verwendet wird, um hier einen Engpass bereits vorab zu
wird, um hier -> Punkt und neuen Satz bitte

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +Virtuellen Instanz verwendet wird, um hier einen Engpass bereits vorab zu
verwendet vs. vorhanden ist? Sonst sieht er ja keine Engpässe oder?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Visualisierung der Auslastung der CPU Leistung für jede einzelne Instanz
Auslastung und Verfügbarkeit

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie soft-IRQ, wait oder interrupt müssen visualisiert
soft-IRQ bitte im gloassar erklären

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie soft-IRQ, wait oder interrupt müssen visualisiert
interrupt -> deutsch -> groß schreiben

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Wie auch bei der CPU Auslastung, gibt es eine solche Auslastung
Vergleichbar wie bei

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Wie auch bei der CPU Auslastung, gibt es eine solche Auslastung
eine solche -> gibt es eine ähnliche Thematik zur Auslastung auch bei

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +zugewiesen ist. Hier kann es ebenfalls wie auch bei der~\ref{subsection:CPU Userstory}
einer Virtuellen Maschine zugewiesen ist -> hattest du doch schon ein Satz vorher geschrieben? Was soll der Satz Aussagen?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Eine frühstmögliche Erkennung von einem Engpass des Arbeitsspeichers einer
Wie das genau?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Ein Onlineshop für zum beispiel Seasonale Ware, wie
zum beispiel -> groß

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +vergangenen Jahr, um hier im kommenden Jahr die Ressourcen bereits bei beginn
beginn groß?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +die Ressourcen verwenden können. In den Monaten, wo keine große Nachfrage
Nebensätze beginnen nicht mit ,wo

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +hat den Vorteil, das spezielle Vertäge dem Kunden angeboten werden kann.
dass

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +hat den Vorteil, das spezielle Vertäge dem Kunden angeboten werden kann.
können?

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Es soll eine Ausgabe in Visualisierter Form über einen bestimmten Monat
Visualisierter  klein

2017-02-04 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Ressourcen, welche benötigt werden, können direkt bereits ab beginn
Beginn groß?

2017-02-05 15:50 UTC, Marcellii commented on thesis-de/content-de.tex
> +dies für eine schnellere Absicherung der Daten. SSDs haben jedoch, wie auch
done

2017-02-05 15:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +HDDs einen Lebenszyklus, der bei SSD schneller erreicht werden kann. Der
done

2017-02-05 15:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +ausgegeben werden, welche SSD von welchem Hersteller in der Wahrscheinlichkeit
Wir haben das so als Wireframe und UserStory definiert gehabt. es kannsein das das mit der Statistik nicht ganz so genauso ist es ist ja so das es nur eine Userstory ist, ist als m.E. kein Kriteriu, welches erfüllt sein muss

2017-02-05 15:53 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Die Ausgabe und Visualisierung in einen Diagramm, ob Balken- oder
done

2017-02-05 15:55 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Die Ausgabe und Visualisierung in einen Diagramm, ob Balken- oder
habs mit welches ersetzt

2017-02-05 15:55 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Auflistung einer Statistik in Form eines Balkendiagramms, über die
s.O.

2017-02-05 15:55 UTC, Marcellii commented on thesis-de/content-de.tex
> +  wenn ein kritischer Schreib- oder Lesezyklus erreicht worden ist.
is weg

2017-02-05 15:56 UTC, Marcellii commented on thesis-de/content-de.tex
> +\\textbf{Name der Story:}\\ Auswertung der CPU Auslastung von jeder Instanz, um Engpässe zu
kann man ja klingt zwar komisch aber Gramatikalisch sollte das richtig sein ohne "vor"

2017-02-05 15:57 UTC, Marcellii commented on thesis-de/content-de.tex
> +\mr%
Ja haben wir auch erstellt.. die Sogenannten Wireframes allerdings muss ich da mit @bastelfreak drüber sprechen, da ich nicht genau weiß wie ich diese dort anbinden kann

2017-02-05 15:59 UTC, Marcellii commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Die CPUs der heutigen Zeit werden immer schneller und besser, von
done

2017-02-05 15:59 UTC, Marcellii commented on thesis-de/content-de.tex
> +Virtuellen Maschine, werden die CPUs jeweils pro Virtueller Maschine zugewiesen,
done

2017-02-05 16:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +so kann eine Maschine 2 CPU Kerne mit z.B. 2,5 GHz Takrate zugewiesen werden.
done

2017-02-05 16:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +unterschiedliche CPUs zugewiesen haben. Manchmal kommt es hier vor, das eine VM
done

2017-02-05 16:07 UTC, Marcellii commented on thesis-de/content-de.tex
> +unterschiedliche CPUs zugewiesen haben. Manchmal kommt es hier vor, das eine VM
done

2017-02-05 16:07 UTC, Marcellii commented on thesis-de/content-de.tex
> +zu viel Rechenleistung, bedingt durch ausgeführte Dienste benötigt. Wenn eine
hab den Satz komplett rausgenommen

2017-02-05 16:17 UTC, Marcellii commented on thesis-de/content-de.tex
> +Virtuellen Instanz verwendet wird, um hier einen Engpass bereits vorab zu
musst du dir bitte nochmal durchlesen.. habs mal versucht zu bearbeiten aber irgendwie kommt da kein guter Satz bei Raus

2017-02-05 16:17 UTC, Marcellii commented on thesis-de/content-de.tex
> +Virtuellen Instanz verwendet wird, um hier einen Engpass bereits vorab zu
done

2017-02-05 16:18 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Visualisierung der Auslastung der CPU Leistung für jede einzelne Instanz
done

2017-02-05 16:18 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie soft-IRQ, wait oder interrupt müssen visualisiert
done

2017-02-05 16:19 UTC, Marcellii commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Wie auch bei der CPU Auslastung, gibt es eine solche Auslastung
done

2017-02-05 16:20 UTC, Marcellii commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Wie auch bei der CPU Auslastung, gibt es eine solche Auslastung
done

2017-02-05 16:22 UTC, Marcellii commented on thesis-de/content-de.tex
> +zugewiesen ist. Hier kann es ebenfalls wie auch bei der~\ref{subsection:CPU Userstory}
hab den Satz davor rausgenommen

2017-02-05 16:27 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Eine frühstmögliche Erkennung von einem Engpass des Arbeitsspeichers einer
was meinst du hier?

2017-02-05 16:27 UTC, Marcellii commented on thesis-de/content-de.tex
> +\\textbf{Beschreibung:}\\ Ein Onlineshop für zum beispiel Seasonale Ware, wie
done

2017-02-05 16:28 UTC, Marcellii commented on thesis-de/content-de.tex
> +vergangenen Jahr, um hier im kommenden Jahr die Ressourcen bereits bei beginn
done

2017-02-05 16:29 UTC, Marcellii commented on thesis-de/content-de.tex
> +die Ressourcen verwenden können. In den Monaten, wo keine große Nachfrage
done

2017-02-05 16:30 UTC, Marcellii commented on thesis-de/content-de.tex
> +hat den Vorteil, das spezielle Vertäge dem Kunden angeboten werden kann.
done

2017-02-05 16:30 UTC, Marcellii commented on thesis-de/content-de.tex
> +hat den Vorteil, das spezielle Vertäge dem Kunden angeboten werden kann.
done

2017-02-05 16:30 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Es soll eine Ausgabe in Visualisierter Form über einen bestimmten Monat
done

2017-02-05 16:30 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Ressourcen, welche benötigt werden, können direkt bereits ab beginn
done

2017-02-05 16:43 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie soft-IRQ, wait oder interrupt müssen visualisiert
ja würd ich gern aber knallt das nicht wenn ich zwei unterschiedlichen Branches in der gleichen Datei an der Gleichen stelle etwas hinzufüge? Ich habe es mir notiert und würde es gern später hinzufügen

2017-02-06 14:19 UTC, StoneCat requested changes
Sorry für die Arbeit :tent:

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +der Wahrscheinlichkeit am häufigsten ausfallen kann.
Also den Punkt sollten wir wiklich nochmal im Team besprechen (hab deinen Kommentar gelesen)

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Die Ausgabe und Visualisierung in einem Diagramm, welches vorzugsweise in
Jetzt beim zweiten mal lesen könnte man doch auch direkt in einem Blaken- oder Graphendiagramm visualisiert schreiben? Jetzt steht das zweimal Diagramm im Text..

Was ist ein Graphendiagramm? Das ist quasi alles -> also Kreis, Balken, Seulen, Plot etc.

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +haben kann. Hier kann es vorkommen, dass eine VM mehr CPU Leistung benötigt, als
Das ist nicht ganz richtig. 
Eine VM hat wirklich nur das was Ihr zugewiesen ist, also ein virtueller Kern. 
Wenn der Kunde nun exterme mathematische Berechnungen durchführt, hat er eben nur die Leistung von einem virtuellen Kern -> muss sich mehr dazu kaufen.

Was du hier meinst ist das der physiche CPU Kern voll ist und auch alle anderen physichen Kerne (Swap nicht mehr möglich). Das kommt aber nur wenn wirklich alle VM's gleichzeitigt arbeiten. 

Trenn das in dem Text besser, sonst wird das eine mit dem anderen verwechselt.

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +Administrator, eine detailierte Übersicht in Form eines Graphen, wieviel CPU
Administrator, eine -> Komma weg

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +Leistung von einer virtuellen Instanz verwendet und vorhanden ist. Dies ist
verwendet wird und auf dem System verfügbar ist.

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +deshalb so wichtig, da wenn eine CPU zu wenig Rechenleistung besitzt, dann kann
Lies den Satz nochmal laut... Macht kein Sinn.

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Visualisierung der Auslastung und Verfügbarkeit der CPU Leistung für jede
Vielleicht müssen wir hier auch nochmal etwas präziser werden. 
Angenommen ein Kern wird x3 virtualisiert, dann hat ein Kern 300 Prozent Leistung, kann aber in Wirklichkeit nur 100 Prozent ausführen. Wenn nun die drei VM's mit jeweils 1 virtuallen Kern (100 Prozent von den 300 Prozent) gleichzeitg die Leistung abrufen, dürfte jeder der VM's nur maximal 33 Prozent der Leistung bekommen, dann erhält jeder 1/3 des echten Kerns (weil ja x3 virtaulisiert).

Das heißt jedoch nicht, dass die VM's niemals auf 100 Prozent kommen können. Angenommen NUR einer der drei VM's greift auf die Leistung zu, dann könnte dieser (solange keine andere VM Leistung anfordert) die 100 Prozent voll nutzen. 

Das sollten wir bei dir hier klar erläutern.

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie \gls{soft-IRQ}, wait oder Interrupt müssen visualisiert
wait und Interrupt ins glossar

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +eine ähnliche Thematik zur Auslastung auch bei dem verwendeten Arbeitsspeicher.
auch eine ... Auslastung bei dem

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +sondern eher wie viel Arbeitsspeicher einer Virtuellen Maschine zugewiesen ist.
Virtuellen klein

2017-02-06 14:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Freien und zwischengespeichertem Arbeitsspeicher, für jede einzelne virtuelle
Freien -> klein

2017-02-06 19:18 UTC, Marcellii commented on thesis-de/content-de.tex
> +der Wahrscheinlichkeit am häufigsten ausfallen kann.
Jap Oke

2017-02-06 19:20 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Die Ausgabe und Visualisierung in einem Diagramm, welches vorzugsweise in
done ich hab das geändert

2017-02-06 19:24 UTC, Marcellii commented on thesis-de/content-de.tex
> +Administrator, eine detailierte Übersicht in Form eines Graphen, wieviel CPU
done

2017-02-06 19:25 UTC, Marcellii commented on thesis-de/content-de.tex
> +Leistung von einer virtuellen Instanz verwendet und vorhanden ist. Dies ist
done

2017-02-06 19:26 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Visualisierung der Auslastung und Verfügbarkeit der CPU Leistung für jede
Ich bin dafür wir sprechen mal genau über die UserStorys

2017-02-06 19:26 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie \gls{soft-IRQ}, wait oder Interrupt müssen visualisiert
siehe kommentar in vorherien commit

2017-02-06 19:27 UTC, Marcellii commented on thesis-de/content-de.tex
> +eine ähnliche Thematik zur Auslastung auch bei dem verwendeten Arbeitsspeicher.
done

2017-02-06 19:27 UTC, Marcellii commented on thesis-de/content-de.tex
> +sondern eher wie viel Arbeitsspeicher einer Virtuellen Maschine zugewiesen ist.
done

2017-02-06 19:28 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Freien und zwischengespeichertem Arbeitsspeicher, für jede einzelne virtuelle
done

2017-02-06 19:33 UTC, Marcellii commented on thesis-de/content-de.tex
> +haben kann. Hier kann es vorkommen, dass eine VM mehr CPU Leistung benötigt, als
hab das mal etwas anders reingeschrieben. Aber wir sollten bedenken es sind UserStorys, meiner Meinung nach gehen die nicht direkt auf die Technische Sicht ein sondenr Beschreiben Oberfläche wie etwas auszusehen hat, bzw. was gewünscht ist z.B. Kunde will SSD Ausfälle sehen oke ja wie realisieren wir das aber halt nicht direkt technisch

2017-02-06 19:35 UTC, Marcellii commented on thesis-de/content-de.tex
> +deshalb so wichtig, da wenn eine CPU zu wenig Rechenleistung besitzt, dann kann
Junge junge junge :D

2017-02-13 19:05 UTC, StoneCat approved these changes

2017-02-18 11:25 UTC, bastelfreak commented on thesis-de/content-de.tex
> +der Wahrscheinlichkeit am häufigsten ausfallen kann.
mal nutzt du SSD's, mal SSDs, letzteres ist korrekt.

2017-02-18 11:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\\textbf{Name der Story:}\\ Anzeige der SSD's, welche einen Hardwaredeffekt haben könnten.
userstories werden immer aus der anwendersicht beschrieben:
http://www.ksimons.de/2015/03/user-stories-verstaendlich-erklaert/

Das englische equivalent hab ich hier im titel https://jira.virtapi.org/browse/DCC-45:
As a system adminsitrator I would like to know if I kill my SSDs
das sollte auch hier genutzt werden, nur auf deutsch.

2017-02-18 11:47 UTC, Marcellii commented on thesis-de/content-de.tex
> +\\textbf{Name der Story:}\\ Anzeige der SSD's, welche einen Hardwaredeffekt haben könnten.
soll ich bei den anderen das auch noch anpassen?

2017-02-18 11:54 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Akzeptanzkriterien:}
nim hier bitte eine subsubsection anstatt einfach nur fett zu machen, das fehlt dann im inhaltsverzeichnis und ist nicht einheitlich mit dem restlichen dokument.

2017-02-18 11:56 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Name der Story:} Anzeige der SSD's, welche einen Hardwaredeffekt haben könnten.
der name stimmt so nicht. stories werden immer aus sicht des anwenders geschrieben.
Mehr infos: http://www.ksimons.de/2015/03/user-stories-verstaendlich-erklaert/

in dem fall: As a system adminsitrator I would like to know if I kill my SSDs (aus https://jira.virtapi.org/browse/DCC-45)

2017-02-18 11:57 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie \gls{soft-IRQ}, wait oder Interrupt müssen visualisiert
haau die anderen begriffe bitte auch ins glossar

2017-02-18 11:58 UTC, bastelfreak commented
bitte auch generell die formatierung prüfen, einige zeilen sind zu lang

2017-02-18 11:59 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie \gls{soft-IRQ}, wait oder Interrupt müssen visualisiert
mhh oke ja habe ich notiert und werde ich gleich in nem extra PR ins Glossar packen und die stellen dann noch anpassen

2017-02-18 12:13 UTC, Marcellii commented on thesis-de/content-de.tex
> +\textbf{Akzeptanzkriterien:}
done

2017-02-18 14:48 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Instanz, um Engpässe zu erkennen.
leerzeile fehlt

2017-02-18 14:49 UTC, bastelfreak commented on thesis-de/content-de.tex
>  \textbf{Beschreibung:} Ein Onlineshop für zum Beispiel Seasonale Ware, wie
leerzeile fehlt

2017-02-18 14:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Beschreibung:} In der heutigen Zeit, werden vermehrt langsame
leerzeile fehlt

2017-02-18 14:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Beschreibung:}\\ Die CPUs der heutigen Zeit werden in der Taktrate und
leerzeile fehlt

2017-02-18 14:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Beschreibung:} Vergleichbar wie auch bei der CPU Auslastung, gibt es
leerzeile fehlt

2017-02-18 14:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Beschreibung:} Ein Onlineshop für zum Beispiel Seasonale Ware, wie
leerzeile fehlt

2017-02-18 14:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Beschreibung:}\\ Dem Administrator oder dem User soll es ermöglicht
leerzeile fehlt, \\ muss weg.

2017-02-18 14:50 UTC, bastelfreak requested changes
siehe inline kommentare

2017-02-18 14:59 UTC, bastelfreak commented on glossary.tex
> +  description={Unter einem iowait definiert man die Aufgabe des Prozessors, bis hier eine
ne. dies beschreibt ob ein Prozessor mit der arbeitung von aufgaben warten muss weil der datenspeicher (Hdds, ssds) nicht mit lesen/schreiben hinterherkommen.

2017-02-18 14:59 UTC, bastelfreak commented on glossary.tex
> +              eines bestimmten Prozess, damit andere Prozesse, welche kürzer abgearbeitet
eines bestimmten Prozesses

2017-02-18 15:01 UTC, bastelfreak commented on glossary.tex
> +              werden können vorrang zu gewähren.}
werden können, oder wichtiger sind, Vorrang bekommen.

2017-02-18 15:01 UTC, bastelfreak commented on glossary.tex
> +              eines bestimmten Prozess, damit andere Prozesse, welche kürzer abgearbeitet
"Unter einem Interrupt versteht man" kann wegfallen

2017-02-18 15:05 UTC, bastelfreak commented on glossary.tex
> +  description={Ein Soft-IRQ wartet auf die \gls{Interrupts} um diese verarbeiten zu können.}
soft-irq und interrupt sind sehr ähnlich. soft-irq wird von programmen ausgelöst, interrupts von hardware

2017-02-18 15:07 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie \gls{Soft-IRQ},\gls{iowait} oder \gls{Interrupt}
wir sollten hier die definitive liste liefern. streich einfach das "wie"

2017-02-18 15:07 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Beschreibung:}\\ Dem Administrator oder dem User soll es ermöglicht
\\\ muss da weg

2017-02-18 15:09 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\\textbf{Name der Story:}\\ Anzeige der SSD's, welche einen Hardwaredeffekt haben könnten.
ja, bei allen.

2017-02-18 15:10 UTC, bastelfreak commented
https://github.com/DCC-org/documents/pull/124/files/fb33f4dbd4f88baf8d6c20a26917d4b33d6fea04#diff-86a189ff2e8f094c4621d6ec10b04bb4 wie hier erwähnt müssen die titel noch angepasst werden

2017-02-18 15:22 UTC, Marcellii commented on glossary.tex
> +  description={Unter einem iowait definiert man die Aufgabe des Prozessors, bis hier eine
done

2017-02-18 15:23 UTC, Marcellii commented on glossary.tex
> +              eines bestimmten Prozess, damit andere Prozesse, welche kürzer abgearbeitet
done

2017-02-18 15:24 UTC, Marcellii commented on glossary.tex
> +              werden können vorrang zu gewähren.}
done

2017-02-18 15:26 UTC, Marcellii commented on glossary.tex
> +  description={Ein Soft-IRQ wartet auf die \gls{Interrupts} um diese verarbeiten zu können.}
done

2017-02-18 15:28 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Alle Werte der CPU, wie \gls{Soft-IRQ},\gls{iowait} oder \gls{Interrupt}
done

2017-02-18 15:38 UTC, bastelfreak commented on glossary.tex
> +              Aufgaben warten muss, weil zum Beispiel der Datenspeicher (HDDs, SSDs)
streich "zum beispiel". das ist der einzige grund warum es iowait gibt

2017-02-18 15:38 UTC, bastelfreak commented on glossary.tex
> +              Prozesses, damit andere Prozesse, welche wichtier sind Vorrang bekommen.
wichtier -> wichtiger

2017-02-18 15:40 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\textbf{Name der Story:} Der Administrator, möchte eine Auswertung der CPU
kein komma nach Administrator

2017-02-18 15:46 UTC, Marcellii commented on glossary.tex
> +              Aufgaben warten muss, weil zum Beispiel der Datenspeicher (HDDs, SSDs)
stimmt :dagger:

2017-02-18 15:47 UTC, Marcellii commented on glossary.tex
> +              Prozesses, damit andere Prozesse, welche wichtier sind Vorrang bekommen.
done

2017-02-18 15:48 UTC, Marcellii commented on thesis-de/content-de.tex
> +\textbf{Name der Story:} Der Administrator, möchte eine Auswertung der CPU
done

2017-02-18 15:50 UTC, bastelfreak approved these changes

2017-02-18 15:50 UTC, merged