Adding section 'OpenTSDB' with first Textinput
DCC-org/documents pull request #125
Opened 2017-02-10 18:02 UTC by StoneCat

2017-02-10 18:02 UTC, StoneCat commented
Ich werde auf die "warum wir das nicht verwenden" in einem späteren Ticket (nächster Sprint) eingehen und in allen Datenbanken spezifischer deklarieren.

2017-02-18 11:41 UTC, Marcellii requested changes
Kleinigkeiten

2017-02-18 11:41 UTC, Marcellii commented on thesis-de/content-de.tex
> +anderen Netzwerkgeräten. Es übernimmt nicht die Aufgabe der Datenspeicherung.
Überles bitte nochmal den Satz Es verfügt über.. der ist irgendwie was Lang und zweimal "und" drin

2017-02-18 11:41 UTC, Marcellii commented on thesis-de/content-de.tex
> +System hängen. Es existiert keinerlei Informationsaustausch zwischen den
anstatt hängen -> angebunden sein

2017-02-18 11:41 UTC, Marcellii commented on thesis-de/content-de.tex
> +einzelnen Deamons, sie nutzen lediglich alle die gleiche Datengrundlage des
sondern nutzen lediglich

2017-02-18 11:41 UTC, Marcellii commented on thesis-de/content-de.tex
> +dynamisch anpassen, da das HBase System stark  auf die Aggregation und niedrigen
zwischen stark und auf ist ein Leerzeichnen zu viel

2017-02-18 11:41 UTC, Marcellii commented on thesis-de/content-de.tex
> +Da unsere Dateninhalte immer in Verbindung mit einem Zeit und Datumswert sind,
sind, und weiter unten wieder und im gleichen Satz klingt nicht so toll

2017-02-18 12:30 UTC, StoneCat commented
Latex build not tested

2017-02-18 12:31 UTC, StoneCat commented
@Marcellii insert your comments into file 
 @bastelfreak please have a look

2017-02-18 12:39 UTC, bastelfreak commented on thesis-de/content-de.tex
> +OpenTSDB ist ein Zeit basiertes Programm, auf englisch ``Time Series Daemon
Timeseries im englischen, Zeitreihe im deutschen, nicht nur "Zeit"

2017-02-18 12:41 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Da unsere Dateninhalte immer in Verbindung mit einem Zeit und Datumswert stehen,
wieder falsche verbform. passive erzählsicht brauchen wir, nicht ich perspektive

2017-02-18 12:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Ziellösung. Jedoch ist die Verwendung von mehreren Serversystemen, welche ggf.
echt? wieso nicht? für redundanz und ausfallsicherheit ist das doch eh notwendig, bei allen systemen?

2017-02-18 14:51 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Dazu wird das zugehörige gls{DBMS} ``HBase'' zwingend benötigt. OpenTSDB wird
\gls und nicht gls

2017-02-18 14:52 UTC, bastelfreak requested changes
siehe inline kommentar, fehlt wohl ein \

2017-02-19 13:29 UTC, bastelfreak approved these changes

2017-02-19 13:30 UTC, merged