(WIP) Implement first comments by David
DCC-org/documents pull request #126
Opened 2017-02-13 17:22 UTC by StoneCat

2017-02-18 11:54 UTC, Marcellii commented on thesis-de/content-de.tex
> +für das abspeichern von mehreren tausend Datensätzen in der Sekunde
Abspeichern in diesem Falle groß

2017-02-18 11:54 UTC, Marcellii commented on thesis-de/content-de.tex
> +werden. Diese Anpassungen können zum Beispiel Funktionen wie das anonymisieren
Funktionen, wie

2017-02-18 14:20 UTC, StoneCat commented
@Marcellii Done
@bastelfreak please have a look

2017-02-18 14:54 UTC, bastelfreak commented on thesis-de/content-de.tex
> +sich wie folgt. Zunächst muss das Datenhaltungssystem
nach "folgt" ggf ein : und neue zeile?

2017-02-18 14:54 UTC, bastelfreak commented on thesis-de/content-de.tex
> +sich wie folgt. Zunächst muss das Datenhaltungssystem
eventuell auch eine aufzählung draus machen mit \outline

2017-02-18 14:56 UTC, bastelfreak requested changes
siehe inline kommentare

2017-02-19 13:32 UTC, bastelfreak approved these changes

2017-02-19 13:32 UTC, merged