Adding sentence @ 'Vorbereitung Eva. API'
DCC-org/documents pull request #140
Opened 2017-02-28 19:56 UTC by StoneCat

Ggf. sollte die angesprochene Liste in den Anhang

2017-02-28 20:01 UTC, bastelfreak commented
welche Liste meinst du in deinem kommentar? Im text sprichst du von einer tabelle, meinst du die?

2017-02-28 20:01 UTC, bastelfreak requested changes
siehe kommentar im PR

2017-03-06 19:01 UTC, StoneCat commented
Ja die Tabelle meine ich

2017-03-22 11:27 UTC, bastelfreak approved these changes

2017-03-22 11:27 UTC, merged