add section acceptance test
DCC-org/documents pull request #168
Opened 2017-03-18 11:15 UTC by Marcellii

2017-03-18 11:38 UTC, Marcellii commented
Was stimmt mit mir nicht :D das DCC ist falsch sollte eigentlich 121 sein statt 120 naja egal

2017-03-18 15:09 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Test Szenarien von \texttt{testkitchen} oder \texttt{serverspec} verwendet und
warum "oder"? Hast du dir die beiden Tools auch mal angeschaut?

2017-03-18 15:10 UTC, bastelfreak commented on thesis-de/content-de.tex
> +dieser Test tatsächlich ausgeführt und geprüft, ob die Funktionalität der
Test -> Tests
tatsächlich streichen

2017-03-18 15:11 UTC, bastelfreak commented on thesis-de/content-de.tex
> +einzelnen Module für den Benutzer gegeben sind. Diese Szenarien prüfen
"gegeben sind" bezieht sich auf "die funktionalität". entweder beides im plural oder beides singular

2017-03-18 15:12 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Funktionen vorhanden sind und funktionieren. Die Ausgabe erfolgt hier entweder
wie genau wird das denn realisiert? ggf beispiele mit drann hängen

2017-03-18 15:17 UTC, bastelfreak commented
https://github.com/voxpupuli/puppet-collectd/tree/master/spec/acceptance acceptance tests für das collectd module

2017-03-19 14:15 UTC, Marcellii commented on thesis-de/content-de.tex
> +Test Szenarien von \texttt{testkitchen} oder \texttt{serverspec} verwendet und
Ja klar das eine ist der Test das andere die Frameworks beide müssen zusammen agieren können

2017-03-19 14:16 UTC, Marcellii commented on thesis-de/content-de.tex
> +dieser Test tatsächlich ausgeführt und geprüft, ob die Funktionalität der
done

2017-03-19 14:18 UTC, Marcellii commented on thesis-de/content-de.tex
> +einzelnen Module für den Benutzer gegeben sind. Diese Szenarien prüfen
done

2017-03-19 15:00 UTC, Marcellii commented on thesis-de/content-de.tex
> +Funktionen vorhanden sind und funktionieren. Die Ausgabe erfolgt hier entweder
done

2017-03-19 15:15 UTC, Marcellii commented on thesis-de/content-de.tex
> +\begin{listing}[H]
ist es in Ordnung das ein so langer Code mitten im Text ist? andernfalls würde ich hier einfach nur einen Auszug beifügen.

2017-03-20 08:55 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\begin{listing}[H]
ist ein bisschen sehr lang, ich würd hier nur zwei tests auflisten und das gesamte ding in den hanhang, falls es auf seine seite passt.

2017-03-21 22:33 UTC, bastelfreak commented on glossary.tex
> +  description={Augeschrieben Client for URL, ist ein Kommandozeilen Programm,
"Client for URL" in quotes setzen

2017-03-21 22:33 UTC, bastelfreak commented on listings/acceptance-test.txt
> +      it { is_expected.to be_running }
formatierung passt nicht. soll nur mit 2 whitespaces eingerückt werden, nicht 4.

2017-03-21 22:40 UTC, bastelfreak commented on listings/full-acceptance-test.txt
> + # Using puppet_apply as a helper
einrückung passt nicht

2017-03-21 22:40 UTC, bastelfreak commented on listings/full-acceptance-test.txt
> + # Run it twice and test for idempotency
einrückung passt nicht

2017-03-21 22:40 UTC, bastelfreak commented on listings/full-acceptance-test.txt
> + # Run it twice and test for idempotency
einrückung passt nicht

2017-03-21 22:44 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Ein Akzeptanz Test prüft den zuvor erstellten Code in einer eigens dafür
ich denke das wird nicht übersetzt. "Acceptance Tests" ist der eingedeutschte fachbegriff

2017-03-21 22:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +System stabil läuft sondern lediglich, ob die einzelnen Funktionen vorhanden
"Es wird hier nicht geprüft, ob das System stabil läuft"
der satz gefällt mir nicht. wie könnte man das denn prüfen? ist das tatsächlich der fall?

2017-03-21 22:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +nicht Bestanden. Anschließend kann der Entwickler diesen Code erneut anpassen
komischer satzbau

2017-03-21 22:47 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\begin{listing}[H]
{H} sollte nicht notwendig sein

2017-03-21 22:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +erhalt eine eigenen Datei, in der definiert ist, mit welcher virtuellen
erhält?

2017-03-21 22:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Maschine oder Container dieser Code ausgeführt werden soll.
die datei in den anhang?

2017-03-21 22:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Ein Akzeptanz Test prüft den zuvor erstellten Code in einer eigens dafür
ah ne. kann deutsch bleiben

2017-03-21 22:49 UTC, bastelfreak requested changes
siehe inline comments

2017-03-22 07:51 UTC, Marcellii commented on listings/full-acceptance-test.txt
> + # Using puppet_apply as a helper
habe ich aus der originalen übernommen, so wie dies in GitHub enthalten ist.

2017-03-22 07:52 UTC, Marcellii commented on listings/full-acceptance-test.txt
> + # Run it twice and test for idempotency
siehe oben

2017-03-22 07:53 UTC, Marcellii commented on listings/full-acceptance-test.txt
> + # Run it twice and test for idempotency
siehe oben

2017-03-22 07:54 UTC, Marcellii commented on thesis-de/content-de.tex
> +Ein Akzeptanz Test prüft den zuvor erstellten Code in einer eigens dafür
hab die Section Beschreibung auf Deutsch nun geschrieben, ich denke das sollte jetzt passen

2017-03-22 07:55 UTC, Marcellii commented on listings/acceptance-test.txt
> +      it { is_expected.to be_running }
habe ich auch angepasst

2017-03-22 07:56 UTC, Marcellii commented on glossary.tex
> +  description={Augeschrieben Client for URL, ist ein Kommandozeilen Programm,
done

2017-03-22 07:57 UTC, Marcellii commented on thesis-de/content-de.tex
> +erhalt eine eigenen Datei, in der definiert ist, mit welcher virtuellen
angepasst

2017-03-22 07:57 UTC, Marcellii commented on thesis-de/content-de.tex
> +\begin{listing}[H]
muss das dann leer bleiben oder ein anderer Buchstabe rein?

2017-03-22 08:02 UTC, Marcellii commented on thesis-de/content-de.tex
> +nicht Bestanden. Anschließend kann der Entwickler diesen Code erneut anpassen
hab den mal ein wenig verändert

2017-03-22 08:03 UTC, Marcellii commented on thesis-de/content-de.tex
> +Maschine oder Container dieser Code ausgeführt werden soll.
jau kann ich machen :dagger:

2017-03-22 08:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +Maschine oder Container dieser Code ausgeführt werden soll.
was genau meinst du damit? die Datei in den Anhang? soll ich einen Beispiel hiervon in den Anhang tun?

2017-03-22 09:51 UTC, bastelfreak commented on glossary.tex
> +               Benutzerinteraktion erforderlich.}
kein punkt am ende

2017-03-22 09:52 UTC, bastelfreak commented on listings/acceptance-test.txt
> +    end
der ganze block darf nicht eingerückt sein. der sollte links bündig starten und nicht mit 2 whitespaces versatz

2017-03-22 09:52 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Ein Akzeptanz Test prüft den zuvor erstellten Code in einer eigens dafür
Name der section sollte dann auch angepasst werden

2017-03-22 09:52 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Test Szenarien von \texttt{testkitchen} und \texttt{serverspec} verwendet und
die begriffe in glossar?

2017-03-22 19:58 UTC, Marcellii commented on glossary.tex
> +               Benutzerinteraktion erforderlich.}
done ist entfernt, da es nicht weiter verwendet wird im content

2017-03-22 20:01 UTC, Marcellii commented on listings/acceptance-test.txt
> +    end
hab jetzt den gesamten Block Linksbündig

2017-03-22 20:42 UTC, StoneCat commented on thesis-de/content-de.tex
> +gestarteten virtuellen Maschine oder Container mit einem Betriebssystem auf die
Wo ist der unterschied zwischen virtuellen Maschine und Container -> verwirrt mich als Leser

2017-03-22 20:42 UTC, StoneCat commented on thesis-de/content-de.tex
> +\label{sec:unit-tests}
Keinen Bindestrich im label

2017-03-22 21:30 UTC, bastelfreak commented on listings/acceptance-test.txt
> + it { is_expected.to be_installed }
das it.. muss mit zwei whitespaces eingerückt sein

2017-03-22 21:40 UTC, Marcellii commented on listings/acceptance-test.txt
> + it { is_expected.to be_installed }
done

2017-03-22 22:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +sein kann.  Anschließend kann der Entwickler diesen Code erneut anpassen und
zwei whitespace

2017-03-22 22:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +testen.  Nachfolgend sind zwei Tests für einen Akzeptanztest für das Modul
zwei whitespace

2017-03-22 22:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Collectd angehangen. Der vollständige Test ist dem Anhang beigefügt.
verlinken

2017-03-23 07:40 UTC, Marcellii commented on thesis-de/content-de.tex
> +sein kann.  Anschließend kann der Entwickler diesen Code erneut anpassen und
done

2017-03-23 07:40 UTC, Marcellii commented on thesis-de/content-de.tex
> +testen.  Nachfolgend sind zwei Tests für einen Akzeptanztest für das Modul
done

2017-03-23 07:48 UTC, Marcellii commented on thesis-de/content-de.tex
> +Collectd angehangen. Der vollständige Test ist dem Anhang beigefügt.
erledigt

2017-03-23 08:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Wie auch für die~\ref{sec:unit_tests} werden Akzeptanztests für verschiedene
bau die pdf mal und les dir das durch. soll das so aussehen? bei einem ref kommt immer nur die nummer der verlinkung, nicht deren name.

2017-03-23 08:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Maschine oder Container dieser Code ausgeführt werden soll.
die datei sollte mit in den anhang

2017-03-23 20:32 UTC, Marcellii commented on thesis-de/content-de.tex
> +Wie auch für die~\ref{sec:unit_tests} werden Akzeptanztests für verschiedene
jau hab ich mal angepasst

2017-03-25 11:55 UTC, bastelfreak commented on listings.tex
> +  \inputminted{ruby}{../listings/def-centos.txt}
yaml oder yml, aber kein ruby.

2017-03-25 12:02 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Collectd angehangen. Der vollständige Test ist dem
collectd, nicht Collectd.

2017-03-25 12:05 UTC, bastelfreak commented on thesis-de/content-de.tex
> +
in dem abschnitt sollte noch erwähnt werden, das nicht nur die einzelnen dienste auf dem system geprüft werden, sondern auch ob puppet idempotent ist und fehlerfrei läuft.

2017-03-25 13:24 UTC, bastelfreak approved these changes

2017-03-25 13:24 UTC, merged