Dcc92 adding notes by dave
DCC-org/documents pull request #169
Opened 2017-03-18 16:05 UTC by StoneCat

2017-03-20 19:32 UTC, bastelfreak commented
sieht gut aus, ich möchte vorhe aber https://github.com/DCC-org/documents/pull/171 mergen.

2017-03-22 09:06 UTC, StoneCat commented
Ready to merge

2017-03-22 09:53 UTC, bastelfreak commented on thesis-de/content-de.tex
> +zu Produkten und Beständen erhält, jedoch keine technisch orientierte Daten.
orientierte -> orientierten

2017-03-22 09:53 UTC, bastelfreak requested changes
ein typo

2017-03-22 10:12 UTC, bastelfreak requested changes

2017-03-22 10:12 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Anschließend dem Aufbau der Tabellen (Schema/Datenhaltungsstruktur) von dem
komischer satzbau

2017-03-22 10:12 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Datenabfragen um ein Vielfaches beschleunigt. Da die Leistung des Clusters durch mehrere Faktoren
zeile zu lang

2017-03-22 11:00 UTC, StoneCat commented on thesis-de/content-de.tex
> +Anschließend dem Aufbau der Tabellen (Schema/Datenhaltungsstruktur) von dem
Das sind die conflicts aus dem master von der Deutschlehrerin, hab es dennoch mal angepasst.

2017-03-22 11:26 UTC, bastelfreak approved these changes

2017-03-22 11:26 UTC, merged