[WIP] Dcc116 postgres and api description
DCC-org/documents pull request #172
Opened 2017-03-22 12:43 UTC by StoneCat

2017-03-22 14:52 UTC, StoneCat commented
Wie stark soll ich bei der API ins Detail gehen?

2017-03-22 15:00 UTC, bastelfreak commented on thesis-de/content-de.tex
> +diesem Prototypen enthält die Kinder-Tabelle „measurement_xMINUS12Hour“ nur
irgendwas stört latex an den quotes. sollen wir hier \texttt{} nutzen?

2017-03-22 19:03 UTC, bastelfreak requested changes

2017-03-22 19:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +einzelnen Nutzer geregelt. Zweiter Nutzer besitzt die Berechtigungen in einem
Der zweite nutzer

2017-03-22 19:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Schreibe Zugriffe auf die in dem definierten Datentopf vorhandenen Tabellen.
Nutzt man datentopf als fachwort?

2017-03-22 19:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +können die Teammitglied an den Inhalten der Datenbank arbeiten.
Teammitglieder

2017-03-22 19:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +eigener Extraktions-, Transformations- und Ladeprozess in das System
Im klammern erwähnen, dass das für ETL steht?

2017-03-22 19:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Dabei findet der Extraktions-Teil zwischen dem erstellten Arbeisbereich und der
ArbeiTs

2017-03-22 20:17 UTC, bastelfreak commented on thesis-de/content-de.tex
> +definierte API-System verwendet. Dieser besitzt keinen direkten Lese oder
definierten

2017-03-22 20:19 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Punkt~\ref{subsec:postgres_datenschutz} erstellten Funktionen. Letzterer Nutzer
"Letzterer Nutzer" klingt komisch

2017-03-22 20:28 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Datensatz mit einem Repositorium, bzw. einem von dem Projektteam definierten
ich weis nicht ob Repositorium ein gängiger begriff ist, eventuell ersetzen oder ins glossar?

2017-03-22 20:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Administration im Wirkbetrieb die Möglichkeit den Dateninput über den
Administrator?

2017-03-22 20:31 UTC, StoneCat commented on thesis-de/content-de.tex
> +Administration im Wirkbetrieb die Möglichkeit den Dateninput über den
done

2017-03-22 20:38 UTC, StoneCat commented on thesis-de/content-de.tex
> +Datensatz mit einem Repositorium, bzw. einem von dem Projektteam definierten
done

2017-03-22 20:49 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Speicherplatzes und Geschwindigkeit und zum anderen das Zusammenhalten der
Vielleicht noch mit einem satz erwähnen warum das schneller ist? Weil nicht alles totnormalisiert wird bis 3NF sondern man eingehende daten direkt so speichert wie sie ankommen. aufgrund des json formats hat man aber weiterhin saubere attribute auf die man selecten kann, als wäre es normalisiert.

2017-03-22 20:51 UTC, bastelfreak commented on thesis-de/content-de.tex
> +kann solch ein Trennung im groben vom Administration definiert werden.
eine

2017-03-22 20:51 UTC, bastelfreak commented on thesis-de/content-de.tex
> +kann solch ein Trennung im groben vom Administration definiert werden.
Administrator?

2017-03-22 20:55 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \inputminted{sql}{../listings/postgres-part-sample.txt}
der code ist etwas lang. ich denke das "DROP TABLE if exists" kann weg. außerdem müssen wir das auf max 80zeichen breite einkürzen.

2017-03-22 20:55 UTC, bastelfreak commented on thesis-de/content-de.tex
> +nur Datensätze bei welchen der Zeitstempel der beinhalteten Daten zwischen dem
"welchen" durch "denen" ersetzen?

2017-03-22 20:56 UTC, Marcellii commented on thesis-de/content-de.tex
> +besitzt keinen direkten Lese oder Schreibe Zugriffe auf die in dem definierten
Lese- oder Schreibzugriffe

2017-03-22 21:03 UTC, bastelfreak commented on thesis-de/content-de.tex
> +jedoch nicht im Detail eingegangen werden.
das ist etwas unglücklich. kannst du den satz streichen? entweder wir ignorieren das komplett oder erwähnen in ein-zwei sätzen was noch fehlt udn stempeln das als lapidar ab.

2017-03-22 21:13 UTC, bastelfreak commented on thesis-de/content-de.tex
> +jedoch nicht im Detail eingegangen werden.
vielleicht noch erwähnen, dass das eventbasiert ist. Es wird also bei jedem insert geprüft von wann der ist, und dann in die jeweile tabelle geschoben. und die muttertabelle ist immer leer. nach aussen hin ist die partitionierung aber transparent und die muttertabelle sieht voll aus.

2017-03-22 21:13 UTC, bastelfreak commented on thesis-de/content-de.tex
> +automatisierten Partitionierung an. Dabei werden die Partionierung von dem
"die Partionierung" -> "die Partitionen"

2017-03-22 21:15 UTC, bastelfreak commented on thesis-de/content-de.tex
> +kann aus dem Postgres-Code im Projektanhang entnommen werden.
wir sollten uns hier irgendwie merken, dass dsa später noch verlinkt wird

2017-03-22 21:17 UTC, bastelfreak commented on thesis-de/content-de.tex
> +kann aus dem Postgres-Code im Projektanhang entnommen werden.
https://jira.virtapi.org/browse/DCC-124

2017-03-22 21:17 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Für den Zugriff auf die in dem Datenhaltsungssystem befindenen Daten wurde von
befindenen -> vorhandenen

2017-03-22 21:19 UTC, bastelfreak commented on thesis-de/content-de.tex
> +analytische Fragestellung, eine eigene Postgres-Funktion bereitgestellt.
http://www.sqlines.com/postgresql/stored_procedures_functions

es sind prozeduren, keine funktionen, oder? Da wir ein oder mehrere result sets zurück geben?

2017-03-22 21:21 UTC, bastelfreak commented on thesis-de/content-de.tex
> +kann. Desweiteren kann der Systemadministrator genau kontrollieren wer auf
kontrollieren,

2017-03-22 21:22 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Funktionen wurden die entsprechenden Marven-Abhängigkeiten eingefügt. Diese
Marven -> Maven

2017-03-22 21:22 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Funktionen wurden die entsprechenden Marven-Abhängigkeiten eingefügt. Diese
Maven ins glossar?

2017-03-22 21:23 UTC, bastelfreak commented on thesis-de/content-de.tex
> +nur mit vier URL's der API. Die erste ist dafür zuständig zu prüfen, ob das
URLs durch Endpunkte ersetzen?

2017-03-22 21:24 UTC, bastelfreak commented on thesis-de/content-de.tex
> +zu anzeigenden Daten zurück. Die letztere ermöglicht es, einzelne Informationen
anzuzeigenden?

2017-03-22 21:24 UTC, bastelfreak commented on thesis-de/content-de.tex
> +
grafana json layout sollte mit in den anhang als quellennachweis

2017-03-22 21:27 UTC, Marcellii commented on thesis-de/content-de.tex
> +Das ist zum Beispeil eine generierte ID, um den Datensatz spezifisch
Beispiel

2017-03-22 21:27 UTC, Marcellii commented on thesis-de/content-de.tex
> +stärke der Partitionierungs-Intervalle an Optimierung verlieren, oder sogar das
die Stärke wird dann glaube ich dann groß geschrieben

2017-03-25 11:37 UTC, bastelfreak commented on thesis-de/content-de.tex
> +diesem Prototypen enthält die Kinder-Tabelle \texttt{measurement_xMINUS12Hour}
warum auch immer muss _ escaped werden:
\texttt{measurement\_xMINUS12Hour}

2017-03-25 11:41 UTC, bastelfreak commented on thesis-de/content-de.tex
> +den Teammitglieder jeweils die benötigte Entwicklerumgebung aufgesetzt
Teammitgliedern

2017-03-25 11:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +implementiert. Die konkrete Umsetzung erfolgte durch das hinzufügen von einem
Hinzufügen

2017-03-25 12:09 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\begin{listing}
das ist ein sehr langes listing, ist schwer das sauber zu positionieren. sollen wir den lieber in den anhang schieben?

2017-03-25 13:07 UTC, bastelfreak approved these changes

2017-03-25 13:07 UTC, merged