scale all pictures to full width
DCC-org/documents pull request #177
Opened 2017-03-25 16:27 UTC by bastelfreak

2017-03-26 10:25 UTC, StoneCat commented
figures/grafana_general.png

-> Alle Bilder haben einen schwarzen Hintergrund außer das, können wir das einheitlich lassen?

2017-03-26 10:26 UTC, StoneCat requested changes
See comment above

2017-04-01 12:57 UTC, bastelfreak commented
find ich okay. @StoneCat hast du da noch irgendwelche bedenken oder kannst du das approven?

2017-04-02 10:12 UTC, StoneCat approved these changes

2017-04-02 10:12 UTC, merged