[WIP] checked requirements
DCC-org/documents pull request #189
Opened 2017-04-01 12:01 UTC by Marcellii

I think i will write something to this

2017-04-23 16:30 UTC, Marcellii commented
i think you can merge that pull request

2017-05-07 15:05 UTC, StoneCat requested changes

2017-05-07 15:05 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Plugins realisiert werden. Die Plugins werden in Javascript geschrieben. Die
Die Plugins werden in Javascript geschrieben -> das ist eine Anforderung?
Kann das Plugin nicht in eine andere Sprache entwickelt werden? Wieso nicht?

2017-05-07 15:05 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \glslink{Dashboard}{Dashboards} durchführen zu können. Das Dashboard
Ist der glslink korrekt?

2017-05-07 15:05 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Beispiel ein externes System (Dateifreigabeserver oder ähnliches) abgelegt
ähnlichem

2017-05-07 15:05 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Webfrontend. Der Auftraggeber und auch die Projektmitglieder selbst,
Software

2017-05-07 15:18 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \glslink{Dashboard}{Dashboards} durchführen zu können. Das Dashboard
ja doch?

2017-05-07 15:23 UTC, bastelfreak requested changes
bitte auch rebasen gegen master

2017-05-07 15:23 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  beinhaltet alle Graphen und vorkonfigurierten Werte. Diese sollen über zum
vorkonfigurierten -> vorkonfigurierte?

2017-05-07 15:23 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Beispiel ein externes System (Dateifreigabeserver oder ähnlichem) abgelegt
"zum Beispiel" streichen

2017-05-07 15:23 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  und einfach (endanwenderspezifisch) direkt angepasst werden können. Ebenso
endanwenderspezifisch -> Endanwenderspezifisch

2017-05-07 15:37 UTC, Marcellii commented
nicht gesehen mit dem rebase

2017-05-07 16:18 UTC, bastelfreak approved these changes

2017-05-08 17:46 UTC, StoneCat approved these changes

2017-05-08 17:46 UTC, merged