Write first text in section api testing
DCC-org/documents pull request #192
Opened 2017-04-16 13:38 UTC by StoneCat

2017-04-18 18:45 UTC, Marcellii requested changes

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Während der Entwicklung des API Systems wurde bei der Implementierung einem
von einem

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +zugehörigen Tests sofort erkennen kann und nicht danach suchen muss.
und hierzu nicht nach diesem suchen muss. ? Klingt eventuell eleganter

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Für das Ausführen der definierten Test muss kein eigene Laufzeit
Tests (Plural)

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Für das Ausführen der definierten Test muss kein eigene Laufzeit
keine (Plural) eigene

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Infrastruktur bereitgestellt werden. Echte Komponententest werden normalerweise
Ich glaube hier wird ebenfalls wieder Plural verwendet vom Komponententests

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +extrem schnell ausgeführt und steigerten durch die Integration in das genannte
steigern

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +verschiedene Definitionen von Objekten in insgesamt verschiedenen
verschiedenen.. ich glaub das kommt 3 Mal in dem Satz vor... Mit dieser können unterschiedliche Einstellungen, .. muss der zwischen Satz dort drin stehen? "beziehungsweise verschiedene Definitionen"

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Laufzeitumgebungen einfach definiert und ausgewählt werden. In unserem Projekt
In dem Projekt

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Testen während der Entwicklung versus dem Zugriff auf die Produktivdaten
testen > kleingeschrieben

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Testen während der Entwicklung versus dem Zugriff auf die Produktivdaten
anstatt "versus" vielleicht "gegenüber von"?

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +dass jeder dieser Profile so funktioniert, wie von dem Entwickeler vorgegeben.
Entwickler

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +getestet, sondern eine aufeinander abgestimmte Reihe von Einzeltest.
Einzeltests?

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Datenhaltsungssystem kann je nach Abfrage sehr lange dauern, um diese
Datenhaltungssystem

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +vorallem wenn die API Daten in dem Datenhaltsungssystem modifizieren, da nach
Datenhaltungssystem

2017-04-18 18:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Transformations- und Ladeprozess vor der Datenhaltung wird neben den
"vor" -> "von"

2017-04-21 10:35 UTC, Marcellii approved these changes

2017-05-07 16:08 UTC, bastelfreak requested changes
bitte auch rebasen

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +parallelen Ordner zu dem Source Code und in der gleichen Programmiersprache wie
ordner -> verzeichnis

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +unserem Fall, nach jeder Änderung am Code ausgeführt werden, ohne das längere
"in unserem fall," -> "in diesem fall"

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Objektdefinitionen. Ein konkretes Beispiel dafür wäre die „Bean“ Definition
wäre -> ist

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +von Swagger. Mit dieser können unterschiedliche Einstellungen, beziehungsweise
Einstellungen von Objekten? Oder nur Definitionen von Objekten?

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Testbibliothek gehört, war das registrieren von verschiedenen API Profilen,
war -> ist

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +sogenannte Integrationstest in der Swagger Testumgebung definieren. Bei
sogenannte löschen

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Bei der Swagger Testbibliothek kann zum Beispiel das korrekte Caching von
Caching -> Zwischenspeichern

2017-05-07 16:08 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Inhalte verwendet werden. In unserem Projekt ist dies die Prüfung der korrekten
unserem -> diesem

2017-05-07 16:32 UTC, bastelfreak approved these changes

2017-05-07 16:32 UTC, merged