Adding grafana mapping table in select functions
DCC-org/documents pull request #204
Opened 2017-05-07 17:21 UTC by StoneCat

2017-05-07 17:39 UTC, bastelfreak requested changes

2017-05-07 17:39 UTC, bastelfreak commented on sql/301_Grafana_Mapping_Create_table.sql
> +  org_id int not null,
index + unique auf die org_id?

2017-05-08 17:49 UTC, StoneCat commented on sql/301_Grafana_Mapping_Create_table.sql
> +  org_id int not null,
Was ist wenn wir mehrere Grafana Systeme haben?
Brauchen wir zu den beiden Tabellen Inhalten oben noch ein "grafana_host" Eintrag in welchem z.B. die IP Adresse des anfragenden Grafana Server steht? 
Oder bekommt jeder Grafana Server eine eigene mapping Tabelle?

2017-05-13 12:49 UTC, bastelfreak commented on sql/301_Grafana_Mapping_Create_table.sql
> +  org_id int not null,
ich sehe da keinen bedarf für. die grafana server würden die gleiche Datenbank nutzen, somit auch immer die gleiche org_id haben. das sollte so out of the box klappen. und ansonsten: das ist eh out of scope. wir haben nur ein grafana.

2017-05-13 15:08 UTC, bastelfreak approved these changes

2017-05-13 15:08 UTC, merged