first review thesis marcellii
DCC-org/documents pull request #235
Opened 2017-05-13 11:58 UTC by Marcellii

2017-05-13 12:55 UTC, StoneCat requested changes
Beim git kommentieren bitte "Abschnitt 1" in der Benennung angeben

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +Die Datenvisualisierung ist zuständig, für die Visualisierung der erhaltenen
der in diesem Projekt erfassten Daten?

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +Daten. Dabei soll dem Benutzer eine Übrsicht über die verbrauchten oder freien
Übrsicht -> Übersicht

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +Ressourcen, wie zum Beispiel CPU-Auslastung oder RAM-Auslastung einzelner
DER CPU-Auslastung

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +werden mit unter sensibele Daten verarbeitet, weshalb hier auf die Sicherheit
sensibele -> sensible

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +in anbetracht auf die Authentifizierung, Authentisierung und Autorisierung
2x auf die
schreib doch einfach "der Authen..."

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +geachtet werden muss. Innerhalb der Projektmeetings wurde die Sicherheit der
Projektmeetings

Tim erklärt irgendwo oben in der PDF den Vorgang der Projektmeetings, vielleicht noch den Ref da rein?

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +Daten diskutiert, weshalb hier ein User Management mit Rechtevergabe, sowie die
diskutiert

Kamen wir auch zu einem Ergebnis? (glaube die Frage würde der STG sich stellen beim lesen)

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +Anbindung an die Datenbank über eine API Schnittstelle realisiert werden muss.
Ref auf meinen neuen Part?

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +Neukonfiguration von virtuellen Maschinen unterstützen und visualisiert hier
hier streichen

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +die Auslastung der einzelnen physischen System in Form von Graphen. Der
Systemen

Ref zu Graphen?

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +Administrator kann so gezielt die einzelnen physischen Maschinen besser
Dem Administrator wird mit Hilfe der Daten ermöglicht, die physischen Maschinen auf eine optimale Auslastung zu bringen. 

Die Frage die ich mir stelle, ist ob du den Satz hier brauchst? Schreiben wir doch schon x Mal in der Doku.

2017-05-13 12:55 UTC, StoneCat commented on thesis-de/content-de.tex
> +"Vorbereitung der Evaluierung für die
In der PDF steht hier dann der von dir eingefügte Name und der Abschnitt Punktwert
Ich glaube du hast hier die falschen Anführungszeichen verwendet, da wird es beim bauen kaputt gehen.

2017-05-13 13:00 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Ressourcen, wie zum Beispiel CPU-Auslastung oder RAM-Auslastung einzelner
muss kein Artikel hin

2017-05-13 13:00 UTC, StoneCat requested changes
Abschnitt 2

2017-05-13 13:00 UTC, StoneCat commented on thesis-de/content-de.tex
> +Eine Schnittstelle auf einem Webinterface dient in erser Linie zur Anzeige von
erser -> erster

2017-05-13 13:00 UTC, StoneCat commented on thesis-de/content-de.tex
> +Daten, die über ein anderes System, beispielsweise aus dem Backend erhalten
Backend ist hier das falsche Wort.
Deine Visualisierungs-Software besitzt ebenfalls ein Backend... Aber da sind ja keine Daten, oder?

2017-05-13 13:04 UTC, StoneCat requested changes
Abschnitt 3

2017-05-13 13:04 UTC, StoneCat commented on thesis-de/content-de.tex
> +siehe Abschnitt "Definition eines Graphen~\ref{definition_eines_graphen}" oder
Anführungszeichen und Name weg

2017-05-13 13:04 UTC, StoneCat commented on thesis-de/content-de.tex
> +direkten Zugriff auf das System besitzen, Analysen oder Statistiken
Analysen durchführen und Statistiken beurteilen.

2017-05-13 13:04 UTC, StoneCat commented on thesis-de/content-de.tex
> +erfolgt mit \gls{HTTPS}. Dies dient zum einem der Verschlüsselung der
Dies dient streichen

Dabei wird die Kommunikation zwischen Browser und Webserver verschlüsselt. 

Das mit dem authentifizieren verstehe ich nicht. Solltest du vielleicht ausschreiben, warum das https macht...

2017-05-13 13:05 UTC, StoneCat commented on thesis-de/content-de.tex
> +Ressourcen, wie zum Beispiel CPU-Auslastung oder RAM-Auslastung einzelner
klingt aber mies ohne

2017-05-13 13:08 UTC, StoneCat requested changes
Abschnitt 4

2017-05-13 13:08 UTC, StoneCat commented on thesis-de/content-de.tex
> +Während der ersten Recherchen für die oben aufgelisteten
glaube den

2017-05-13 13:08 UTC, StoneCat commented on thesis-de/content-de.tex
> +direkt mit dem Projektteam besprochen und aufgenommen werden. Zusätzlich zu der
mhm. Ich schreibe bei der Datenhaltung das wir es zwingend mit dem Auftraggeber abstimmen müssen. Du nur im Team. 

Ich weiß nicht was für den Rösch "nach genauen Projektmanagment-Vorgaben" das richtige ist

2017-05-13 13:08 UTC, StoneCat commented on thesis-de/content-de.tex
> +aufgenommen. Diese werden für die eigentliche Durchführung der Evaluierung und
und aufgenommen streichen

2017-05-13 13:13 UTC, StoneCat requested changes
Abschnitt 5

2017-05-13 13:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +Innerhalb der Datenvisualisierungslösung werden dem User oder dem Administrator
vielleicht solltest du mal das ganze Dokument durchschauen und User mit Benutzer austauschen. 
Ist ja schließlich in deutsch hier

2017-05-13 13:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +SSD-Schreibzugriffe visualisiert. Diese Graphen können entweder in Linerar-
gls zu ssd?

2017-05-13 13:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +oder Balkenform dargestellt werden. Lineare Graphen haben eine X- und Y-Achse
Warum so komplziert?
Diese Daten werden optimalerweise in einem Balken-, Säulen- oder Liniendiagramm dargestellt.

2017-05-13 13:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +oder Balkenform dargestellt werden. Lineare Graphen haben eine X- und Y-Achse
ah okay wenn man weiterliest versteht man den Satz

2017-05-13 13:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +Weboberfläche aus den Datenhaltungssystemen abgreift, erstellt und kann vom
erstellt. neuer Satz

2017-05-13 13:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +Balkendiagramme haben nur eine X-Achse, wo der gewünschte Analysewert
"wo" ist kein schönes Deutsch

2017-05-13 13:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +eingetragen ist und werden z.B. für ausgefallene SSDs in einem bestimmten
gls auf ssd?

2017-05-13 13:20 UTC, StoneCat requested changes
Abschnitt 6

2017-05-13 13:20 UTC, StoneCat commented on thesis-de/content-de.tex
> +der Anforderungen eine Realisierbarkeit besitzen. Nachdem die einzelnen
Realisierbarkeit stört mich ein wenig.

Kannst du nicht in 1 2 sätzen schreiben, was in diesem Projekt denn realisierbar wäre. 
muss während der Beurteilung beachtet werden, dass diese innerhalb dem Projekt zur Verfügung stehenden Zeit realisierbar sind. Dabei wird das prüfen, testen, realisieren etc. bla bla mit beachtet

2017-05-13 13:20 UTC, StoneCat commented on thesis-de/content-de.tex
> +zusammengefasst und Gewichtet. Nachfolgenden können die einzelnen Kriterien
Gewichtet wirklich groß?

Im nachfolgenden?

2017-05-13 13:22 UTC, Marcellii commented on thesis-de/content-de.tex
> +geachtet werden muss. Innerhalb der Projektmeetings wurde die Sicherheit der
hab gerade mal geschaut habe kein Absatz gefunden wo Tim meetings anspricht  höchstens unter der agilen Vorgehnsweise das passt aber nicht meines erachtens

2017-05-13 13:32 UTC, StoneCat reviewed
Abschnitt 7

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  "Anforderungen~\ref{section:anforderungen} definiert, muss die zu
Anführungszeichen weg

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Evaluieriende Softwarelösung eine Open-Source-Lizenz besitzen, damit hier der
Evaluieriende klein

hier streichen

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Projekts oder später beim Kunden anfallen können.
und somit beim Kunden anfallen können.

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Um die Sicherheit und den zugriff auf das Webinterface gewährleisten zu
zugriff groß

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  können, muss an die Datenvisualisierung die Anforderung gestellt werden, das
Der Satz ist auch wieder zu sehr verschachtelt mit Kommas.

dass

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Dies dient in erster Linie die Daten, sowie die Anmeldung an dem Webinterface
Diese dienen in erster Linie

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  entweder über einen lokalen Administrator, als auch über eine LDAP-Anbindung
gls auf LDAP

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  (Lightweight Directory Access Protocol) verfügen, um hier zum Beispiel
hier streichen

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +Sicherheit
Vielleicht subsubsections oder mit Tim sprechen was an Überschriften geht...

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  der Community oder aber durch selbst programmierte Plugins realisiert werden.
aber auch durch

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Unabhängigkeit von Entwicklern gewährleisten zu können. Unternehmen müssen so
ist das echt so?
Die Plugins brauchen doch immer irgendwie javascript oder css? Wir sind hier ja im webbereich?
Kann ich in Grafana echt Plugins in java, R oder C schreiben?

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  muss die Anbindung an eventuell schon vorhandene Datenbanksysteme beim Kunden
Vielleicht noch der Satz, dass die anderen DB-Systeme nichts mit dem Projekt zu tun haben. Aber für gaaaaanz andere Daten mit integriert werden können.

2017-05-13 13:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Nun sind hier insgesamt 64 Graphen, welche sekündlich eine Abfrage an das
Du beschreibst zwar hier das Problem, aber nicht die von uns angeforderte Lösung... 
Was soll das Teil denn können, damit die API/Datenhaltung nich mit 64 Anfragen gleichzeitig zugeballert wird?
Lese das irgendwie nicht aus dem Text.. Wenn die Lösugn deine ersten drei Sätze sind, stell das bitte um

2017-05-13 13:33 UTC, Marcellii commented on thesis-de/content-de.tex
> +Administrator kann so gezielt die einzelnen physischen Maschinen besser
ich würd das eventuell lassen und wo anders aus der Doku streiten weil das ist der Anfang der Doku wo man sowas eventuell noch nicht wissen könnte?

2017-05-13 13:41 UTC, StoneCat requested changes
Abschnitt 8

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +Softwarelösung nicht weiter verwendeti werden kann. Gridster-D3 ist bereits
verwendet

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +anderen Diensten, weshalb diese im Fehlerfall zu Probleme verursachen könnte.
zu streichen

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +Anders als bei Grafana, welches mit mehreren Datenbanken gleichzeitig
mehreren Datenbanken gleichzeitig kommunizieren kann
Ist das nicht ein passender Satz für deine Anforderungen?

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +so betrifft dies das gesamte Graphite-System und die Weboberfläche wäre nicht
so streichen

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +mehr erreichbar. Zusätzlich ist hier gerade in der Wartung der Dienste ein
hier streichen

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +besteht, benötigt Graphite auch mehr Systemressourcen als ein einzelner Dienst,
Mal ne Frage am Rande?
Können diese mehreren Dienste auf verschiedenen Servern ausfgeführt werden?
Wenn ja, ist das doch ein dicker Vorteil?

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +Sicherheit
\textbf würde auch gehen?

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +sorgt dies für einen schnelleren Datenzugriff. SSDs haben jedoch, wie auch
wenn du ssd und hdd ins glossar aufnimmst hier gls einbauen

2017-05-13 13:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +handelsüblichen HDDs. Der Administrator soll hier darüber benachrichtigt
hier streichen

2017-05-13 13:52 UTC, StoneCat requested changes
Abschnitt 9

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +der Webseite besteht, können hier weniger Ressourcen dr virtuellen Maschine
der

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Ressourcen, welche benötigt werden können direkt bereits ab Beginn
das Kommar war richtig

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Die Graphen, der Visualisierung kann über den benutzer oder dem
Benutzer

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +Befehle abweichen. Die zu unterstützen Distributionen, können der Grafana
An der Stelle ist die Frage, ob wir eigentlich im Pflichtenheft definiert habe nauf welchem System das alles laufen soll?

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +von Grafana wird bereits ein vordefinierter Administrator User mit Passwort
Benutzer

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +für den Administrator oder User negativ beeinflussen.
Benutzer

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +Graphen visuell dargestellt werden können. Unter dem Abschnitt "Graphen
Anführungszeichen und Name weg

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +definieren~\ref{subsec:graphen-definieren}" wird hier genauer auf die
hier streichen

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +hier abgefragten Daten wurden aus einer InfluxDB erhalten:
Die in dem Bild zu sehenen abgefragten

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +Konfigurationn nicht verloren gehen können. Sollte das Speichern vom
können streichen

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +abgespeichert werden.  Damit wie in dem Projekt gefordert eine API
leerzeichen nach dem Punkt zu viel

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +dem Reiter Admin > Global Users weitere User angelegt werden und
Benutzer

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +übergeben. Das Puppet Profil prüft hier den Login auf das Webinterface nicht,
hier streichen

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +da es davon ausgeht, dass das die Anmeldemaske des Webinterface unmittelbar
eins der beiden das streichen sollte doch ausreichen?

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +Soabld die Grundkonfiguration von Grafana wie im Abschnitt "Realisierung
Anführungszeichen und Name weg

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +können als nächstes Graphen visualisiert werden.
die Graphen?

2017-05-13 13:52 UTC, StoneCat commented on thesis-de/content-de.tex
> +können als nächstes Graphen visualisiert werden.
visualisierst du die oder das System? 
Eher das System... du konfigurierst nur

2017-05-13 13:58 UTC, Marcellii commented on thesis-de/content-de.tex
> +besteht, benötigt Graphite auch mehr Systemressourcen als ein einzelner Dienst,
fällt eins aus so ist das System nicht Funktional dabei spielt es keine Rolle ob sie auf anderen Servern ausgelagert sind ;)

2017-05-13 14:03 UTC, StoneCat requested changes
Abschnitt 10

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +zu Webseiten hinterlegt werden. Diese werden anschließend, wie im
bisschen viel werden in einem Abschnitt

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +Erhaltung eine HTTPS-~\gls{API} Schnittstelle verwendet, welche im Laufe des
https gls

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +sondern über eine \gls{HTTPS} Schnittstelle. Innerhalb der API werden bereits
gls api

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +Administrator dienen, da dieser die Minimalen- und Maximalenwerte, sowie
Minimal- und Maximalwerte

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +Aktuellen- und Durchnittswerte welche innerhalb der Analyse ausgegeben worden
Aktuelle-

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +sind sehen kann. Ein Beispiel hierzu ist dem Anhang~\ref{figure:grafana_legend}
sind, sehen

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +wodurch bei einem kritischen Wert eine Benachrichtigung versendet werden kann.
wird

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +Damit diese Funktion verwendet werden kann, muss diese Funktion zum einen in
können

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +der Allgemeinen Konfiguration unter dem Reiter Alerting konfiguriert werden und
allgemeinen klein

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +kann anschließend beispielsweise über Email oder die Messenger Telegram oder
den Messenger

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +kann anschließend beispielsweise über Email oder die Messenger Telegram oder
Zweimal oder

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +Threema erfolgen. Weitere Kommunikationswege sind hier ebenfalls möglich.
Weitere Kommunikationswege sind hier ebenfalls möglich

würde ich weg lassen oder sowas wie "durch das installieren weiterer Plugins" schreiben

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +werden kann. Ein Beispiel hierzu ist dem Anhang~\ref{figure:grafana_alert}
werden soll

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +beigefügt. Die Bedingung, die Konfiguriert werden kann, muss entwender einen
Konfiguriert klein

welche konfiguriert

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +Zusätzlich kann definiert werden, über welchen Kommunikationsweg die
Zusätzlich wird/muss definiert

2017-05-13 14:03 UTC, StoneCat commented on thesis-de/content-de.tex
> +der rechten Oberen Hälfte von Grafana kann die Allgemeine zu visualisierende
oberen klein

2017-05-13 14:20 UTC, Marcellii commented on thesis-de/content-de.tex
> +Sicherheit
mhh muss Tim entscheiden ist aber auch schnell hinzugefügt ;)

2017-05-13 14:31 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Unabhängigkeit von Entwicklern gewährleisten zu können. Unternehmen müssen so
ich würde den kompletten Satz streichen da er sich absolut komisch anhört grafana beispielsweise kann nur java...
aber wie verpacke ich das am besten :/

2017-05-13 15:10 UTC, StoneCat commented
- [ Correct Abschnitt 1] 
- [ Correct Abschnitt 2] 
- [ Correct Abschnitt 3] 
- [ Correct Abschnitt 4] 
- [ Correct Abschnitt 5] 
- [ Correct Abschnitt 6] 
- [ Correct Abschnitt 7] 
- [ Correct Abschnitt 8] 
- [ Correct Abschnitt 9] 
- [ Correct Abschnitt 10]

2017-05-13 15:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +Die Datenvisualisierung ist zuständig, für die Visualisierung der erhaltenen
done

2017-05-13 15:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +Daten. Dabei soll dem Benutzer eine Übrsicht über die verbrauchten oder freien
done

2017-05-13 15:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +Ressourcen, wie zum Beispiel CPU-Auslastung oder RAM-Auslastung einzelner
done

2017-05-13 15:13 UTC, StoneCat commented on thesis-de/content-de.tex
> +werden mit unter sensibele Daten verarbeitet, weshalb hier auf die Sicherheit
done

2017-05-13 15:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +in anbetracht auf die Authentifizierung, Authentisierung und Autorisierung
done

2017-05-13 15:15 UTC, StoneCat commented on thesis-de/content-de.tex
> +Projektmeetings wurde die Sicherheit der Daten diskutiert, dabei ging es hier
hier streichen

2017-05-13 15:15 UTC, StoneCat commented on thesis-de/content-de.tex
> +Daten diskutiert, weshalb hier ein User Management mit Rechtevergabe, sowie die
done

2017-05-13 15:16 UTC, StoneCat commented on thesis-de/content-de.tex
> +Administrator kann so gezielt die einzelnen physischen Maschinen besser
da steht es schon.
done.

2017-05-13 15:17 UTC, StoneCat requested changes
Abschnitt 1 1

2017-05-13 15:17 UTC, StoneCat commented on thesis-de/content-de.tex
> +festgelegt, das ein User Management mit Rechtevergabe, sowie die Anbindung an
User -> Benutzer

2017-05-13 15:17 UTC, StoneCat commented on thesis-de/content-de.tex
> +die Datenbank über eine API Schnittstelle(siehe
Komma vor Klammer auf
fehlende Klammer zu

2017-05-13 15:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +Eine Schnittstelle auf einem Webinterface dient in erser Linie zur Anzeige von
done

2017-05-13 15:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +Daten, die über ein anderes System, beispielsweise aus dem Backend erhalten
done

2017-05-13 15:21 UTC, StoneCat commented on thesis-de/content-de.tex
> +siehe Abschnitt "Definition eines Graphen~\ref{definition_eines_graphen}" oder
done
(ggf. später mal die Zeile wieder auf 80 Zeichen bringen, muss nicht in diesem PR gemacht werden)

2017-05-13 15:21 UTC, StoneCat commented on thesis-de/content-de.tex
> +direkten Zugriff auf das System besitzen, Analysen oder Statistiken
done

2017-05-13 15:23 UTC, StoneCat requested changes
Abschnitt 3 1

2017-05-13 15:23 UTC, StoneCat commented on thesis-de/content-de.tex
> +kann, wie es bei einer (Man-in-the-middle) Attacke der Fall wäre.
kann.
Das abgreifen der Kommunikation wird im Fachkreis auch Man-in-the-middle genannt.

2017-05-13 15:23 UTC, StoneCat commented on thesis-de/content-de.tex
> +erfolgt mit \gls{HTTPS}. Dies dient zum einem der Verschlüsselung der
done

2017-05-13 15:24 UTC, StoneCat commented on thesis-de/content-de.tex
> +Während der ersten Recherchen für die oben aufgelisteten
done

2017-05-13 15:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +musste durch den Auftraggeber zugestimmt werden. Erst nachdem dieser zugestimmt
musste? haben wir denn eins hinzugefügt? Oder meinst du "muss"?
Erst nachdem dieser zustimmt, kann eine weitere hinzugefügt werden.

2017-05-13 15:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +direkt mit dem Projektteam besprochen und aufgenommen werden. Zusätzlich zu der
halb done -> neuer Kommentar in 4 1

2017-05-13 15:27 UTC, StoneCat requested changes
Abschnitt 4 1

2017-05-13 15:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +aufgenommen. Diese werden für die eigentliche Durchführung der Evaluierung und
hast du vergessen

2017-05-13 15:29 UTC, StoneCat commented on thesis-de/content-de.tex
> +Innerhalb der Datenvisualisierungslösung werden dem User oder dem Administrator
done

2017-05-13 15:31 UTC, StoneCat commented on thesis-de/content-de.tex
> +Datenhaltungssystemen abgreift erstellt. Diese kann vom Administrator ebenfalls
abgreift, erstellt

2017-05-13 15:31 UTC, StoneCat commented on thesis-de/content-de.tex
> +Weboberfläche aus den Datenhaltungssystemen abgreift, erstellt und kann vom
done

2017-05-13 15:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +nur für eine definierte Zeitspanne angezeigt werden.  Balkendiagramme haben nur
zu viele Leerzeichen nach dem.

2017-05-13 15:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +z.B. für ausgefallene SSDs in einem bestimmten Zeitraum verwendet. Diese werden
z.B. ausschreiben

2017-05-13 15:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +Balkendiagramme haben nur eine X-Achse, wo der gewünschte Analysewert
done

2017-05-13 15:32 UTC, StoneCat requested changes
Abschnitt 5 1

2017-05-13 15:32 UTC, StoneCat commented on thesis-de/content-de.tex
> +RAM-Auslastung oder SSD-Schreibzugriffe visualisiert. Diese Graphen können
gls auf ssd?

2017-05-13 15:36 UTC, StoneCat commented on thesis-de/content-de.tex
> +innerhalb dem Projekt zur Verfügung stehenden Zeit realisierbar sind. Dabei
dem im Projekt

2017-05-13 15:36 UTC, StoneCat commented on thesis-de/content-de.tex
> +wird das prüfen, testen, sowie realisieren der einzelnen Kriterien beachtet.
Prüfen, Testen, sowie Realisieren

nichteinfach abschrieben
mit bla bla meinte ich:
Realisieren in der Zeitabschätzung der einzelnen Kriterien beachtet wird
Oder hatl ganz anders geschrieben, denk einfach beim schreiben nach...

2017-05-13 15:36 UTC, StoneCat commented on thesis-de/content-de.tex
> +der Anforderungen eine Realisierbarkeit besitzen. Nachdem die einzelnen
siehe Abschnitt 6 1

2017-05-13 15:37 UTC, StoneCat commented on thesis-de/content-de.tex
> +zusammengefasst und Gewichtet. Nachfolgenden können die einzelnen Kriterien
done

2017-05-13 15:37 UTC, StoneCat reviewed
Abschnitt 6 1

2017-05-13 17:23 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Unabhängigkeit von Entwicklern gewährleisten zu können. Unternehmen müssen so
habs umgeschrieben ;)

2017-05-13 18:11 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Nun sind hier insgesamt 64 Graphen, welche sekündlich eine Abfrage an das
hab ich umgeschrieben sieht so besser aus

2017-05-13 18:24 UTC, Marcellii commented on thesis-de/content-de.tex
> +Befehle abweichen. Die zu unterstützen Distributionen, können der Grafana
ich glaube das ist nirgends definiert :D

2017-05-13 18:28 UTC, Marcellii commented on thesis-de/content-de.tex
> +dem Reiter Admin > Global Users weitere User angelegt werden und
das ding heißt Global Users
vielleicht texttt?

2017-05-13 18:49 UTC, Marcellii commented on thesis-de/content-de.tex
> +wird das prüfen, testen, sowie realisieren der einzelnen Kriterien beachtet.
passt so finde ich persönlich

2017-05-13 19:48 UTC, Marcellii commented on thesis-de/content-de.tex
> +Damit diese Funktion verwendet werden kann, muss diese Funktion zum einen in
können? ist können nicht mehrzahl aber hierbei handelt es sich um Einzahl :O

2017-05-13 19:50 UTC, Marcellii commented on thesis-de/content-de.tex
> +Threema erfolgen. Weitere Kommunikationswege sind hier ebenfalls möglich.
wollte damit eigentlich gesagt haben das Threema und Telegram nicht die einzelnen sind sondern auch Slack angesprochen werden kann oder ähnliche

2017-05-13 20:16 UTC, Marcellii commented on thesis-de/content-de.tex
> +der Anforderungen eine Realisierbarkeit besitzen. Nachdem die einzelnen
habe ich eigentlich gemacht also ich finde es für mich in Ordnung würde ich sagen das Realisierbarkeit ist dort raus

2017-05-14 17:30 UTC, bastelfreak requested changes

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Die Datenvisualisierung ist zuständig, für die Visualisierung der in diesem
Datenvisualisierung visualisiert Daten. Das ist etwas offensichtlich. Außerdem kommt da kein komma hin

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +weshalb hier auf die Sicherheit in anbetracht auf der Authentifizierung,
auf die Authentifizierung

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +ermöglicht es, den Zugriff nur für die Datenvisualisierung auf die sensibelen
sensibelen -> sensiblen

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Auslastung der einzelnen physischen Systemen in Form von Graphen(siehe
Leerezichen vor (

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Abfragen und Analysen bereitstellen. Bei Bedarf können diese auch visuell
Erst wird von Graphen gesprochen, dann von komplexen Abfragen (kann das überhaupt irgendein System? Dafür haben wir die API von Nikolai?). Zum schluss geht es um visuelle Ausgabe. Erster und letzter Punkt sind redundant.

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Abschnitt~\ref{subsec:definition_eines_graphen})Der Administrator kann so
. und Leerzeichen hinter )

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +
keine leerzeile zwischen kürzel und absatz

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Datenhaltung, wie auch die eigentliche Datenvisualisierung gewährleistet werden
"wie auch der Datenvisualisierung" <- dann bezieht sich die Sicherheit auf die Datenvisualisierung

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Eine Schnittstelle auf einem Webinterface dient in erster Linie zur Anzeige von
was genau willst du in den beiden sätzen ausdrücken?

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +liefert dem Webinterface alle nötigen Funktionen und Werkzeuge zur
Warum der wechsel von deutsch zu englisch?

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +liefert dem Webinterface alle nötigen Funktionen und Werkzeuge zur
ah lol, das ist eingedeutscht und steht im duden.

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Webserver verschlüsselt, sodass diese durch dritte nicht abgegriffen werden
dritte -> Dritte

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +kann. Das abgreifen der Kommunikation wird im Fachkreis auch Man-in-the-middle
Man-in-the-middle -> Man-in-the-Middle-Angriff

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Innerhalb der Datenvisualisierungslösung werden dem Benutzer oder dem
Aus Sicht der Datenvisualisierungslösung ist jeder, der das System benutzt, ein Benutzer. Hier muss also nicht explizit zwischen Benutzer und Administrator unterschieden werden. Ein Administrator ist nur ein spezieller Benutzer mit bestimmten Zugriffsrechten.

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +innerhalb dem im Projekt zur Verfügung stehenden Zeit realisierbar sind. Dabei
dem -> der

2017-05-14 17:30 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Wie bereits in der Grundanforderung unter
"Wie bereits definiert..." kann gestrichen werden, das sind nur Füllworter. Bei einer Auflistung sind weniger Worte immer besser

2017-05-15 16:06 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Um die Sicherheit und den zugriff auf das Webinterface gewährleisten zu
done

2017-05-15 16:10 UTC, StoneCat commented on thesis-de/content-de.tex
> +  können, muss an die Datenvisualisierung die Anforderung gestellt werden, das
done

2017-05-15 16:10 UTC, StoneCat commented on thesis-de/content-de.tex
> +  entweder über einen lokalen Administrator, als auch über eine LDAP-Anbindung
done

2017-05-15 16:11 UTC, StoneCat commented on thesis-de/content-de.tex
> +  (Lightweight Directory Access Protocol) verfügen, um hier zum Beispiel
done

2017-05-15 16:11 UTC, StoneCat commented on thesis-de/content-de.tex
> +  muss die Anbindung an eventuell schon vorhandene Datenbanksysteme beim Kunden
done

2017-05-15 16:17 UTC, StoneCat commented on thesis-de/content-de.tex
> +handelsüblichen HDDs. Der Administrator soll hier darüber benachrichtigt
done

2017-05-15 16:17 UTC, StoneCat commented on thesis-de/content-de.tex
> +sorgt dies für einen schnelleren Datenzugriff. SSDs haben jedoch, wie auch
done

2017-05-15 16:18 UTC, StoneCat commented on thesis-de/content-de.tex
> +der Webseite besteht, können hier weniger Ressourcen dr virtuellen Maschine
done

2017-05-15 16:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Ressourcen, welche benötigt werden können direkt bereits ab Beginn
done

2017-05-15 16:19 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Die Graphen, der Visualisierung kann über den benutzer oder dem
done

2017-05-15 16:20 UTC, StoneCat commented on thesis-de/content-de.tex
> +von Grafana wird bereits ein vordefinierter Administrator User mit Passwort
done

2017-05-15 16:20 UTC, StoneCat commented on thesis-de/content-de.tex
> +für den Administrator oder User negativ beeinflussen.
done

2017-05-15 16:23 UTC, StoneCat commented on thesis-de/content-de.tex
> +Soabld die Grundkonfiguration von Grafana wie im Abschnitt "Realisierung
done

2017-05-15 16:23 UTC, StoneCat commented on thesis-de/content-de.tex
> +können als nächstes Graphen visualisiert werden.
Siehe 9 1

2017-05-15 16:24 UTC, StoneCat commented on thesis-de/content-de.tex
> +zu Webseiten hinterlegt werden. Diese werden anschließend, wie im
done

2017-05-15 16:26 UTC, StoneCat commented on thesis-de/content-de.tex
> +Erhaltung eine HTTPS-~\gls{API} Schnittstelle verwendet, welche im Laufe des
done

2017-05-15 16:26 UTC, StoneCat commented on thesis-de/content-de.tex
> +sondern über eine \gls{HTTPS} Schnittstelle. Innerhalb der API werden bereits
done

2017-05-15 16:27 UTC, StoneCat commented on thesis-de/content-de.tex
> +Administrator dienen, da dieser die Minimalen- und Maximalenwerte, sowie
done

2017-05-15 16:39 UTC, Marcellii commented on thesis-de/content-de.tex
> +Eine Schnittstelle auf einem Webinterface dient in erster Linie zur Anzeige von
Was bei einer Schnittstelle grundsätzlich ist bei einem Webinterface

2017-05-15 17:04 UTC, StoneCat approved these changes

2017-05-15 17:05 UTC, closed without merging