Fix Issues Thesis proof reading
DCC-org/documents pull request #249
Opened 2017-05-16 11:10 UTC by Marcellii

2017-05-17 20:14 UTC, StoneCat requested changes

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Datenvisualisierung, durch ein API System gesteigert.
mhm, wohl auch die Datenhaltungs Performance steigert sich

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +  definiert, dass eine Aktive und inhaltlich gute Community vorrausgesetzt
aktive

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +  definiert, dass eine Aktive und inhaltlich gute Community vorrausgesetzt
nim qualität anstatt gut

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
>    keine große Schulung mit dem Umgang der Datenvisualisierung. Dies erleichtert
mit dem -> für den

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +bestimmte Teilabschnitte mit zum Beispiel Social\hyp{}Media\hyp{}Plattformen
Soziale Netzwerke ist das deutsche Wort.

Wobei twitter unter Microblog fällt, ist kein soziales Netzwerk ;D

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +gibt es hier einen \gls{IRC-Channel}, um direkt Kontakt mit dem Support
hier streichen

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +da diese im Quellcode der Webseite verändert und angepasst werden müssen.  Ein
doppelt Leerzeichen

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +Instanz gleichzeitig überwachen kann und der Vorteil bei Netdata, dass kein
ist,

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +Netdata, wurde auch hier eine Nutzwertanalyse durchgeführt, die wie folgt
hier streichen

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +empfängt Metriken von \gls{Agents}, bereitet diese auf und speichert diese
zweite diese = die

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +welches mit mehreren Datenbanken gleichzeitig kommunizieren kann.  Innerhalb
Doppelt Leerzeichen

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +Drives im weiteren \gls{HDD} durch schnellere Solid State Disks im weiteren\gls
Was soll dieses weiteren? Das gehört da nicht hin

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +unter „Data Sources“ sein, so wird hier „Data Sources“ eingeblendet. Dies soll
hier = an der (vorgesehenen) Stelle

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +Menü, wo der grundsätzliche Aufbau, die Metrik, die Axen und diverse weitere
Sätze beginnend mit wo sind kein deutsch

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +Organisations\hyp{}IDs. Somit erhalten diese Zugriff auf die Dateninhalte des
Sind das nicht meine Sätze??

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +beigefügt. Zusätzlich kann hier auch die entsprechende Einheit für diese Werte
hier streichen

2017-05-17 20:14 UTC, StoneCat commented on thesis-de/content-de.tex
> +definiert. Eingestellt werden kann hier welchen Minimal\hyp{}, Maximal\hyp{},
Es kann dort eingestellt werden welchen ....

2017-05-17 20:33 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Datenvisualisierung, durch ein API System gesteigert.
da ist das schon geschrieben hatte kann das da raus

2017-05-17 20:46 UTC, Marcellii commented on thesis-de/content-de.tex
> +unter „Data Sources“ sein, so wird hier „Data Sources“ eingeblendet. Dies soll
was meinst du damit?

2017-05-17 20:47 UTC, Marcellii commented on thesis-de/content-de.tex
> +Organisations\hyp{}IDs. Somit erhalten diese Zugriff auf die Dateninhalte des
ja die hatten doch gefehlt!

2017-05-18 16:33 UTC, StoneCat commented on thesis-de/content-de.tex
> +unter „Data Sources“ sein, so wird hier „Data Sources“ eingeblendet. Dies soll
Goldfischgehirn

2017-05-18 16:33 UTC, StoneCat commented on thesis-de/content-de.tex
> +Organisations\hyp{}IDs. Somit erhalten diese Zugriff auf die Dateninhalte des
done

2017-05-18 16:38 UTC, StoneCat requested changes

2017-05-18 16:38 UTC, StoneCat commented on thesis-de/content-de.tex
> +  benötigen keine große Schulung mit den Umgang der Datenvisualisierung. Dies
mit = für

2017-05-18 16:38 UTC, StoneCat commented on thesis-de/content-de.tex
> +Community, in der viele inhaltliche Dokumente enthalten sind, sind hier nur für
enthalten sind, sind hier -> klingt kacke

2017-05-18 16:50 UTC, StoneCat approved these changes

2017-05-18 17:05 UTC, merged