Dcc23
DCC-org/documents pull request #51
Opened 2016-11-02 19:38 UTC by StoneCat

@DCC-org/team 

Ticket:
https://jira.virtapi.org/browse/DCC-23

2016-11-02 19:59 UTC, bastelfreak requested changes

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Projektmitgliedern aus vergangenen Projekten, bzw. aus dem täglichen
keine abkürzungen, "bzw." bitte ausschreiben

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Experten aus dem Freundeskreis und Arbeitsumfeld über mögliche
"Freundeskreis" entfernen.  ggf erwähnen dass der auftraggeber Puppet auch vorgaben gemacht hat

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +worden, welche im Bereich der sogenannten BIG DATA Technologie
wir sollten ein neues kapitel anlegen, es glossar nennen, und 'BIG DATA' da reinschreiben. Sollte die schreibweise nicht 'Big Data' sein?

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +mehrere Kriterien definiert, welche uns einen Leitpfaden für die
du ändert die verbform hier, bleib bei passiv.
"...wurden mehrere Kriterien definiert, welche einen Leitpfaden für die  spätere Arbeit geben."
Konjunktiv soll vermieden werden sofern er nicht notwendig ist (in dem fall 'sollen').

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Datenbanksystems der Projektmitglieder sowie die Mitarbeiter
Datenbanksystems -> Datenbanksystem

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  dem Projekt und im späteren Wirkbetrieb bei Mitarbeitern des
Genetiv oder Dativ? Keine Ahnung

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Aufstockung nach einer Auszeit von maximal 45 Minuten erfolgt ist.
wieso 45min? Im zweifelsfall 'Vorgabe vom Auftraggeber sind max 45min' oder sowas

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Die Verwendung von einem statischen System ist, in Hinsicht der oben
was meinst du mit 'statischem system'?

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Hardware und dem daraus resultierendem Resultat. Eine
"resultierendem Resultat" ist doppelt. "resultierendem Ergebnis"?

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Die Datenhaltungs-Software sollte bereits über Methoden zur
s/über//

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Datensicherung besitzen. Dabei ist zum einem eine BackUp Methodig,
s/BackUp Methodig/Backup Methode/

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  und zum anderen das Verhalten bei Problemen am System, z.B.
"z.B." ausschreiben. Was genau meinst du hier? Das system soll backups machen wenn das kabel kaputt geht?

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +handelt, sondern um ein mächtiges Werkzeug zur Datenanalyse,
s/mächtiges//

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Bei der Evalution von den anderen Datenhaltungssystemen konnten
s/Evalution/Evaluation/

2016-11-02 19:59 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\label{subsec:datenbanksysteme}
*eigentlich* kann man auch links auf die überschrift machen und muss kein extra label setzen, muss ich mal nachgucken.

2016-11-02 20:04 UTC, Marcellii reviewed
See the reviews

2016-11-02 20:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +  dass dieses eine umfangreiche Dokumentation besitzt und z.B. eine
I think diese

2016-11-02 20:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Datenbanksystems der Projektmitglieder sowie die Mitarbeiter
Projektmitglieder, sowie

2016-11-02 20:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +  der genutzen Stromeffiziensklasse jedes Hardwarebauteils bereits
genutzten

2016-11-02 20:04 UTC, Marcellii commented on thesis-de/content-de.tex
> +Massendatenhaltungssysteme arbeitet, sind ebenefalls Systeme aufgenommen
ebenfalls

2016-11-06 09:44 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  dass diese eine umfangreiche Dokumentation besitzt und z.B. eine
"z.B." entfernen.

2016-11-06 09:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Dies ist im Bereich der Datenhaltungs-Software zum Beispiel die
"zum Beispiel" entfernen

2016-11-06 10:03 UTC, bastelfreak approved these changes

2016-11-06 10:03 UTC, merged