Modify "Evaluierung Frontend" in Doc
DCC-org/documents pull request #66
Opened 2016-11-09 15:02 UTC by Marcellii

I have create the point "Evaluierung des Frontends" in dem Thesis Doc.

2016-11-14 21:54 UTC, StoneCat requested changes
@Marcellii Done. 
Unterstütze gerne bei Textbausteinen.

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +Bevor das Projekt beginnen konnten, musste zusammen mit dem Auftraggeber und
Entweder "wir das Projekt" oder "konnte".

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +Bevor das Projekt beginnen konnten, musste zusammen mit dem Auftraggeber und
War das wirklich mit dem Auftraggeber? Ist die Liste vollständig im Pflichtenheft, oder hatten wir während dem Projekt weitere Systeme hinzugefügt?

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +verwendet wird. Diese Liste besteht zum Teil aus Software Lösungen, welche im
verwendet werden. Du beziehst dich auf die Anforderung nicht auf die Liste der Systeme...

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +verwendet wird. Diese Liste besteht zum Teil aus Software Lösungen, welche im
Du wirfst hier "Anforderungen" und "Liste aus Software Lösungen" komplett durcheinander. Versuche das eine zu schreiben, bevor du mit dem anderem beginnst. Oder entderne "diese".

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +eigenen Unternehmen, bereits erfolgreich eingesetzt worden sind und zum anderen
Aha, also haben wir doch eigene Systeme hinzugefügt. Versuch das alles im ersten Absatz zu erläutern, bevor du von den Anforderungen redest.

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +von Vorschläge des Auftraggebers. Während der Planung des Frontends, kamen noch
Während der  Evaluierungsphase... ggf. ein Satz wie "nach Absprache im Team" oder "nach Absprache mit dem Auftraggeber" wurden diese hinzugefügt/mit betrachtet.

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +Dies benötigte keine Zustimmung des Auftraggebers, sondern konnte mit dem
Bring den Satz nach oben in den anderen Absatz.

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +Folgende Frontends wurden während der Planung, bereits vorab mit dem
Ich würde zwei Listen machen, oder klar sagen, welche Softwarelösungen wir vorab im Pflichtenheft stehen hatten und welche dazu gekommen sind.

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +\subsection{Vorbereitung der Evaluierung}
ist eine \subsubsection

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +die Frontends erfüllen müssen. (Diese sollen später für eine bessere
Verusch mal ein anderes Wort zu verwenden. Frontend ist der Bereich -> das Ergebnis
Softwarelösung oder Software oder Applikation -> Das Werkzeug für das Ergebnis. 
Verwende eins der Wörter auch oben bei der Auflistung in Zeile 378

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +Übersichtlichkeit dienen, welche Anforderungen das Frontend haben muss). Bei
Keine Klammern. Entweder in einem Satz oder es ist keine wichtige Information. Bitte generell versuchen in Dokumentationen keine ganzen Sätze in Klammern zu formulieren. 
Zudem ist der Satzbau mieserabel :( 
Diese Kriterien, in Form von definierten Anforderungen, sollen für eine besser Übsericht während der Evaluierung dienen.

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +den Kriterien, musste darauf geachtet werden, dass diese zu Projektübergabe
zur

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +den Kriterien, musste darauf geachtet werden, dass diese zu Projektübergabe
Nicht zur Projektübergabe, sondern bei der Beurteilung der Systeme in der Evaluierung.
Wir können ja nicht am Ende des Projektes mit leeren Händen kommen und sagen während der Evaluierung traf keine Anforderung ins grüne, sodass wir nun kein Frontend besitzen. 

Beispiel:
, dass diese während der Beurteilung der Anforderungen eine Machbarkeit und Realistik besitze,

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +Anschluss von jedem einzelnen Projektmitglied auf die Machbarkeit und
Was meinst du mit Durchführung?
Durchführung klingt so komisch. Die Sache ist durchführbar. -> ist aber korrekt weil substantiv, gibt es da noch ein anderes Wort?

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  gewährleistet werden. Dies bedeutet, dass die Daten und damit auch die View
View wäre ein Fachwort und müsste ins Glossar... Oder du verwendest ein deutsches Wort

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  vor ungeschützten Zugriff dritter geschützt sein muss. Ebenfalls müssen die
durch dritter

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Daten selber, welche von dem Frontend abgegriffen werden, vor dritter
die übertragenen Daten?

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  werden können und je nach Kundenanforderung auch Self Signed Zertifikate
Entwender direkt beschreiben was das heißt oder ins Glossar

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Administrator, als auch über eine LDAP(Lightweight Directory Access Protocol)
Entwender direkt beschreiben was das heißt oder ins Glossar (Ausformulieren)

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  \1 Eine gute und große Community und Dokumentation über das Webfrontend.
"eine gute"
Das ist meiner Meinung nach nicht beurteilbar, was heißt schon gut?
Ist gut = viel Inhalt
ist gut = qualitative inhalte -> wollen wir die Community auf Wahrheit der Inhalte prüfen?
ist gut = etc. pp?

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Visualisierung von CPU, RAM, Netzwerk oder ähnliche Datenwerte. Hiermit ist
Du hast in zwei Absätzen "hiermit ist gemeint" geschrieben -> leicht uncool

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  gemeint das Gewährleistet werden muss, dass  die einzelnen Graphen schnell
An der Stelle kommt mir die Frage auf, wie sieht so ein Frontend überhautp aus. 
Du erwähnst nun das erste mal "Graphen". Irgendwo musst du den genauen Aufbau beschreiben und auch warum wir uns für den Aufbau entschieden haben. Am besten dann von hier aus darauf Verweisen.

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Ebenso muss die Anbindung an eventuell bereits schon vorhandene
ggf. hier dann ein Verweis an die API

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Dabei muss das Frontend, bereits schon Möglichkeiten bieten, eine
Als leihe verstehe ich nicht, warum das Frontend eine Datensicherung braucht, wenn alle Daten auf dem Datenbankserver liegen. Meinst du hier die Software-Daten, also das was im www Ordner liegt?

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  Dabei blablabla (hier muss nochwas hin, fällt mir gerade aber nicht ein)
Ist meiner Meinung nach der gliche Punkt wie in Zeile 421 bis 426

2016-11-14 21:54 UTC, StoneCat commented on thesis-de/content-de.tex
> +  bereits beim Kunden eingesetzt wird, auf bestimmte Kundenwünsche direkt
Plugins werden dann in welcher Entwicklersprache entwickelt?
Ist es wichtig das es eine gängie Sprache ist? Hat das Unternehmen bereits Entwickler in der Sprache? 
Bevorzugt das Unternehmen eine Sprache der Erweiterungen? Wie viel/weit darf Erweitert werden? Wo sind Grenzen?

2016-11-20 12:09 UTC, Marcellii commented on thesis-de/content-de.tex
> +Bevor das Projekt beginnen konnten, musste zusammen mit dem Auftraggeber und
done

2016-11-20 12:14 UTC, Marcellii commented on thesis-de/content-de.tex
> +Bevor das Projekt beginnen konnten, musste zusammen mit dem Auftraggeber und
done

2016-11-20 12:16 UTC, Marcellii commented on thesis-de/content-de.tex
> +verwendet wird. Diese Liste besteht zum Teil aus Software Lösungen, welche im
stimmt habe ich angepasst, das ich mich hier auf die Software Liste selber beziehe nicht auf die Anforderungsliste

2016-11-20 12:17 UTC, Marcellii commented on thesis-de/content-de.tex
> +verwendet wird. Diese Liste besteht zum Teil aus Software Lösungen, welche im
habe ich angepasst

2016-11-20 12:21 UTC, Marcellii commented on thesis-de/content-de.tex
> +eigenen Unternehmen, bereits erfolgreich eingesetzt worden sind und zum anderen
habs angepasst

2016-11-20 12:25 UTC, Marcellii commented on thesis-de/content-de.tex
> +von Vorschläge des Auftraggebers. Während der Planung des Frontends, kamen noch
angepasst

2016-11-20 12:27 UTC, Marcellii commented on thesis-de/content-de.tex
> +Dies benötigte keine Zustimmung des Auftraggebers, sondern konnte mit dem
ist nach oben

2016-11-20 12:35 UTC, Marcellii commented on thesis-de/content-de.tex
> +Folgende Frontends wurden während der Planung, bereits vorab mit dem
angepasst

2016-11-20 12:36 UTC, Marcellii commented on thesis-de/content-de.tex
> +\subsection{Vorbereitung der Evaluierung}
done

2016-11-20 12:37 UTC, Marcellii commented on thesis-de/content-de.tex
> +die Frontends erfüllen müssen. (Diese sollen später für eine bessere
hab mich für Softwarelösungen geeinigt ich denke das passt da.. weil Frontend kann eventuell nicht jeder etwas mit anfangen.

2016-11-20 12:41 UTC, Marcellii commented on thesis-de/content-de.tex
> +Übersichtlichkeit dienen, welche Anforderungen das Frontend haben muss). Bei
habs angepasst

2016-11-20 12:42 UTC, Marcellii commented on thesis-de/content-de.tex
> +den Kriterien, musste darauf geachtet werden, dass diese zu Projektübergabe
done

2016-11-20 12:46 UTC, Marcellii commented on thesis-de/content-de.tex
> +den Kriterien, musste darauf geachtet werden, dass diese zu Projektübergabe
klingt besser

2016-11-20 20:32 UTC, Marcellii commented on thesis-de/content-de.tex
> +Anschluss von jedem einzelnen Projektmitglied auf die Machbarkeit und
ja Realisierbarkeit wäre eine Alternative

2016-11-20 20:34 UTC, Marcellii commented on thesis-de/content-de.tex
> +  gewährleistet werden. Dies bedeutet, dass die Daten und damit auch die View
Weboberfläche

2016-11-20 20:34 UTC, Marcellii commented on thesis-de/content-de.tex
> +  vor ungeschützten Zugriff dritter geschützt sein muss. Ebenfalls müssen die
done

2016-11-20 20:50 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Daten selber, welche von dem Frontend abgegriffen werden, vor dritter
habs ein wenig abgeändert... und hier gesagt das die Verbindung, welche das Frontend nutzt gesichert sein muss vor dritter

2016-11-20 20:51 UTC, Marcellii commented on thesis-de/content-de.tex
> +  werden können und je nach Kundenanforderung auch Self Signed Zertifikate
done

2016-11-20 20:53 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Administrator, als auch über eine LDAP(Lightweight Directory Access Protocol)
Habs rausgenommen mit Self Signed Zertifikaten, da das an dieser stelle eigentlich schwachsinnig ist... Die ANmeldung sollte per HTTPS sein und Zertifikate sollen möglich sein

2016-11-20 21:03 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Eine gute und große Community und Dokumentation über das Webfrontend.
Eine Inhaltlich gute und Umfangreiche Community und Dokumentation

2016-11-20 21:05 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Visualisierung von CPU, RAM, Netzwerk oder ähnliche Datenwerte. Hiermit ist
angepasst

2016-11-20 21:06 UTC, Marcellii commented on thesis-de/content-de.tex
> +  gemeint das Gewährleistet werden muss, dass  die einzelnen Graphen schnell
Wird das nicht im Interface Beschreibung UI abgefrühstückt? habe ich mir als Punkt notiert und wird noch hinzugefügt

2016-11-20 21:09 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Ebenso muss die Anbindung an eventuell bereits schon vorhandene
hab ich gemacht

2016-11-20 21:10 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Dabei muss das Frontend, bereits schon Möglichkeiten bieten, eine
Eigentlich das Dashboard selber... diese können aber abgespeichert und somit gesichert werden. Einfach dafür wenn die Weg sind, das der Admin hier nicht nochmal das komplette Dashboard friemeln muss. Ich habs jetzt umgeschrieben, das es eindeutig ist, das hier das Dashboard gemeint ist

2016-11-20 21:15 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Dabei blablabla (hier muss nochwas hin, fällt mir gerade aber nicht ein)
hab den kompletten Punkt API entfernt. Da API eigentlich nur CURL oder Ähnlichem ist.

2016-11-20 21:24 UTC, Marcellii commented on thesis-de/content-de.tex
> +  bereits beim Kunden eingesetzt wird, auf bestimmte Kundenwünsche direkt
habs mal versucht zu schreiben

2016-11-21 17:42 UTC, bastelfreak requested changes

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Bevor wir das Projekt beginnen konnten, mussten vorab zusammen mit dem
falsche verbform. passiv dritte person.

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Nach Absprache mit dem Projektteam, sind noch folgende in Frage kommende
leerzeile einfügen

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Das Hinzufügen, von weiteren
leerzeile einfügen

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Das Hinzufügen, von weiteren
zeilenumbruch entfernen

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Softwarelösungen, während der Evaluierungsphase bedarf keine weitere Zustimmung
'keiner weiteren Zustimmung'

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +für die Evaluierung der einzelnen Frontends verwendet wird. Die zu Evaluierende
Evaluierende -> evaluierende

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +von Vorschläge des Auftraggebers.
von Vorschläge -> aus Vorschlägen

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Unternehmen, bereits erfolgreich eingesetzt worden sind und zum anderen
'eingesetzt worden sind' oder 'eingesetzt werden'? Grafana läuft bei mir produktiv

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Softwareliste besteht zum Teil aus Softwarelösungen, welche im eigenen
"eigenen" -> falsche verbform

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Damit die Evaluierung der einzelnen Softwarelösungen durchgeführt werden konnten,
konnten -> können
präsens

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Die Anmeldung am Frontend kann entweder über einen Lokalen Administrator, als
fehlt da ein \1?

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Eine Inhaltlich gute und Umfangreiche Community und Dokumentation über das
Inhaltlich -> inhaltlich

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Eine Inhaltlich gute und Umfangreiche Community und Dokumentation über das
Umfangreiche -> umfangreiche

2016-11-21 17:42 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\end{outline}
erwähnen das es FOSS sein muss

2016-11-21 17:55 UTC, Marcellii commented on thesis-de/content-de.tex
> +Nach Absprache mit dem Projektteam, sind noch folgende in Frage kommende
done

2016-11-21 17:56 UTC, StoneCat approved these changes

2016-11-21 17:57 UTC, Marcellii commented on thesis-de/content-de.tex
> +Bevor wir das Projekt beginnen konnten, mussten vorab zusammen mit dem
done

2016-11-21 17:57 UTC, Marcellii commented on thesis-de/content-de.tex
> +Das Hinzufügen, von weiteren
done

2016-11-21 17:58 UTC, Marcellii commented on thesis-de/content-de.tex
> +Softwarelösungen, während der Evaluierungsphase bedarf keine weitere Zustimmung
done

2016-11-21 18:00 UTC, Marcellii commented on thesis-de/content-de.tex
> +für die Evaluierung der einzelnen Frontends verwendet wird. Die zu Evaluierende
done

2016-11-21 18:02 UTC, Marcellii commented on thesis-de/content-de.tex
> +Softwareliste besteht zum Teil aus Softwarelösungen, welche im eigenen
done

2016-11-21 18:02 UTC, Marcellii commented on thesis-de/content-de.tex
> +Unternehmen, bereits erfolgreich eingesetzt worden sind und zum anderen
done

2016-11-21 18:03 UTC, Marcellii commented on thesis-de/content-de.tex
> +von Vorschläge des Auftraggebers.
done

2016-11-21 18:05 UTC, Marcellii commented on thesis-de/content-de.tex
> +Damit die Evaluierung der einzelnen Softwarelösungen durchgeführt werden konnten,
done

2016-11-21 18:06 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Die Anmeldung am Frontend kann entweder über einen Lokalen Administrator, als
glaube nicht, weil dies noch zur Authentisierung/Authentifiezierung gehört eigentlicht.

Das Spätere Produkt muss alle drei sachen unterstützen

2016-11-21 18:07 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Eine Inhaltlich gute und Umfangreiche Community und Dokumentation über das
done

2016-11-21 19:46 UTC, bastelfreak requested changes

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Das Hinzufügen, von weiteren Softwarelösungen, während der Evaluierungsphase
Kein komma nach hinzufügen. Steht das auch so im Lasten/Pflichtenheft?

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +mit dem Projektteam besprochenund aufgenommen werden. Zusätzlich zu der Liste
besprochenund -> besprochen und

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Das Hinzufügen von weiteren Softwarelösungen, während der Evaluierungsphase
das steht schon im absatz drüber

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +der Anforderungen eine Machbarkeit und Realistik besitze. Nachdem die einzelnen
Realistik steht nicht im duden

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +der Anforderungen eine Machbarkeit und Realistik besitze. Nachdem die einzelnen
komischer satzbau

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Weboberfläche selber vor ungeschützten Zugriff durch dritter geschützt sein
was ist "ungeschützten Zugriff"?

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Weboberfläche selber vor ungeschützten Zugriff durch dritter geschützt sein
das klingt nach Autorisierung, was ist mit den anderen beiben begriffen.

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  über ein gesichertes HTTPS Protokoll durchgeführt werden können und je nach
'ein HTTPS Protokoll'? HTTPS ist keine protokollfamilie sondern das Protokoll. 'Als Transportverschlüsselung wird HTTPS genutzt'

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Kundenanforderung auch eigene Zertifikate zulassen.
was meinst du mit 'eigenen Zertifikaten'? Client-Zertifikate? Selbstsignierte?

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  sollen über z.B. ein externes System (FileServer o.a.) abgelegt werden
FileServer übersetzen oder genauer spezifizieren

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Die Datensicherung muss einen wesentlichen Aspekt bei dem Frontend sein.
'ist ein wesentlicher/essentieller Aspekt'

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  \1 Plugin Erweiterung. Das Frontend, muss eine Plugin Erweiterung
im glossar ergänzen was ein Plugin und was ein Addon ist

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  eingehen zu können und diese Mittels bereits schon zur Verfügung gestellte
satz viel zu lang

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  Die Weboberfläche sollte jedoch auch andere Sprachen unterstützen, um so eine
sicher? Kann das überhaupt irgendein system?

2016-11-21 19:46 UTC, bastelfreak commented on thesis-de/content-de.tex
> +  sein. Ebenfalls dient eine Open Source Software, dass der Quelltext der
'dient eine Open Source Software'? Wem oder was dient die?

2016-11-22 20:59 UTC, Marcellii commented on thesis-de/content-de.tex
> +Das Hinzufügen von weiteren Softwarelösungen, während der Evaluierungsphase
done

2016-11-22 21:00 UTC, Marcellii commented on thesis-de/content-de.tex
> +mit dem Projektteam besprochenund aufgenommen werden. Zusätzlich zu der Liste
done

2016-11-22 21:00 UTC, Marcellii commented on thesis-de/content-de.tex
> +Das Hinzufügen, von weiteren Softwarelösungen, während der Evaluierungsphase
was meinst du genau hier? Das Softwarelösungen frei hinzugefügt werden können ohne Probleme ?

2016-11-22 21:02 UTC, Marcellii commented on thesis-de/content-de.tex
> +der Anforderungen eine Machbarkeit und Realistik besitze. Nachdem die einzelnen
komischer Satz in der Tat. müsste nochmal überarbeitet werden.

2016-11-22 21:05 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Weboberfläche selber vor ungeschützten Zugriff durch dritter geschützt sein
habs angepasst

2016-11-22 21:05 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Das Hinzufügen, von weiteren Softwarelösungen, während der Evaluierungsphase
Im Lasten/Pflichtenheft ist definiert wie änderungen eingebracht werden dürfen, bist du sicher, das man die liste einfach so ergänzen kann? Hast du lasten/Pflichtenheft geprüft?

2016-11-22 21:06 UTC, Marcellii commented on thesis-de/content-de.tex
> +  über ein gesichertes HTTPS Protokoll durchgeführt werden können und je nach
habs angepasst

2016-11-22 21:11 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Kundenanforderung auch eigene Zertifikate zulassen.
habs angepasst und gesagt das es Client Zertifikate sind.. eigentlich meinte ich hier SSL Zertifikate welche die Webseite absichern soll. Ich glaube man nennt es Portal HTTPS Zertifikate

2016-11-22 21:14 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Die Datensicherung muss einen wesentlichen Aspekt bei dem Frontend sein.
hab den Satz angepasst

2016-11-22 21:15 UTC, Marcellii commented on thesis-de/content-de.tex
> +  sollen über z.B. ein externes System (FileServer o.a.) abgelegt werden
Dateifreigabe Server ... eventuell kommt FileServer noch ins Glossar wenn dies genehm ist

2016-11-22 21:16 UTC, Marcellii commented on thesis-de/content-de.tex
> +  \1 Plugin Erweiterung. Das Frontend, muss eine Plugin Erweiterung
wird im Glossar hinzugefügt

2016-11-22 21:19 UTC, Marcellii commented on thesis-de/content-de.tex
> +  eingehen zu können und diese Mittels bereits schon zur Verfügung gestellte
Hab den Satz gekürzt

2016-11-22 21:21 UTC, Marcellii commented on thesis-de/content-de.tex
> +  Die Weboberfläche sollte jedoch auch andere Sprachen unterstützen, um so eine
Wenn ich das so richtig lese:

http://docs.grafana.org/plugins/development/

Unter dem Punkt What Languages? heißt es für mich irgendwie das es angeblich egal wäre welche Sprache...

Also eigentlich Java Script aber angeblich kannste dir auch ne Sprache auchsuchen.

2016-11-22 21:22 UTC, Marcellii commented on thesis-de/content-de.tex
> +  sein. Ebenfalls dient eine Open Source Software, dass der Quelltext der
done

2016-11-22 21:31 UTC, bastelfreak approved these changes

2016-11-22 21:40 UTC, merged