Add section define a graph
DCC-org/documents pull request #87
Opened 2016-11-23 16:56 UTC by Marcellii

I have define the graph section

2016-11-23 16:57 UTC, bastelfreak commented on thesis-de/content-de.tex
> +von z.B. CPU Auslastung, RAM Auslastung oder SSD Lese- Schreibzugriffe
Schreibzugriffen

2016-11-23 16:57 UTC, bastelfreak commented on thesis-de/content-de.tex
> +von z.B. CPU Auslastung, RAM Auslastung oder SSD Lese- Schreibzugriffe
Schreibzugriffen

2016-11-23 17:01 UTC, bastelfreak requested changes

2016-11-23 17:01 UTC, bastelfreak commented on thesis-de/content-de.tex
> +von z.B. CPU Auslastung, RAM Auslastung oder SSD Lese- Schreibzugriffe
Schreibzugriffen

2016-11-23 17:01 UTC, bastelfreak commented on thesis-de/content-de.tex
> +zusätzlich einen Anfang und einen wachsenden Endpunkt. Er wird mittels SQL
Nicht alle möglichen Datenbanken sprechen SQL

2016-11-23 17:01 UTC, bastelfreak commented on thesis-de/content-de.tex
> +angezeigt. Diese Graphen, werden entweder in Linerarer oder Balkenform
Graphen werden... ohne komma

2016-11-23 17:01 UTC, bastelfreak commented on thesis-de/content-de.tex
> +angezeigt. Diese Graphen, werden entweder in Linerarer oder Balkenform
linerarer

2016-11-23 17:01 UTC, bastelfreak commented on thesis-de/content-de.tex
> +über eine Übersicht angezeigt.
ich hab irendwo weiter oben definiert was eine Timeseries und eine Metrik ist. Ein Graph visualisiert immer eine oder mehrere Timeseries. Denke das sollte her irgendwo ergänzt werden.

2016-11-23 17:18 UTC, Marcellii commented on thesis-de/content-de.tex
> +von z.B. CPU Auslastung, RAM Auslastung oder SSD Lese- Schreibzugriffe
done

2016-11-23 17:19 UTC, Marcellii commented on thesis-de/content-de.tex
> +angezeigt. Diese Graphen, werden entweder in Linerarer oder Balkenform
done

2016-11-23 17:20 UTC, Marcellii commented on thesis-de/content-de.tex
> +zusätzlich einen Anfang und einen wachsenden Endpunkt. Er wird mittels SQL
mhh hier eventuell sagen mit einer Syntax oder besser mit einem Befehl (Oberflächlich) bleiben?

2016-11-23 17:23 UTC, Marcellii commented on thesis-de/content-de.tex
> +zusätzlich einen Anfang und einen wachsenden Endpunkt. Er wird mittels SQL
bzw. Metrik

2016-11-23 17:28 UTC, Marcellii commented on thesis-de/content-de.tex
> +über eine Übersicht angezeigt.
habe es als letzten Satz noch beigepackt

2016-11-23 17:38 UTC, bastelfreak requested changes

2016-11-23 17:38 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Metrik~\ref{subsubsection:Begriffserklärung} ,welche die Weboberfläche aus den
leerzeichen muss nach dem komma, nicht davor

2016-11-23 17:38 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Datenhaltungssystemen abgreift erstellt und kann vom Administrator ebenfalls
abgreift, erstellt

2016-11-23 17:38 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Auf der Weboberfläche werden dem User oder dem Administrator einzelne Graphen,
das ist mehr eine beschreibung was ein graph in unserem projekt ist.

hast du noch das C buch von mir rumfliegen? da gabs eine gute erklärung drinn was ein (mathematischer) graph ist. Eine verbindung von koordinaten auf einem raster oder sowas. eine koordinate ist bei uns eine messung/messwert aus einer timeseries. auf der einen achse dann der tatsächliche wert, auf der anderen der timestamp der aufnahme.

2016-11-23 17:42 UTC, Marcellii commented on thesis-de/content-de.tex
> +Auf der Weboberfläche werden dem User oder dem Administrator einzelne Graphen,
ja habe ich schaue ich nachher mal nach. Bin noch nicht zu Hause Darf das aus dem Buch quasi zitiert werden? eigentlich ja schon muss halt nur als Quelle angegeben werden

2016-11-23 17:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Metrik~\ref{subsubsection:Begriffserklärung} ,welche die Weboberfläche aus den
habs angepasst

2016-11-23 17:45 UTC, Marcellii commented on thesis-de/content-de.tex
> +Datenhaltungssystemen abgreift erstellt und kann vom Administrator ebenfalls
habs angepasst

2016-11-23 19:21 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Auf der Weboberfläche werden dem User oder dem Administrator einzelne Graphen,
direkt zitieren würd ich nicht. Buch lesen, in eigenen worten wiedergeben und dann quelle angeben. wenn du mir die ISBN gibst kann ich das in biblatex einbauen.

2016-11-23 20:12 UTC, Marcellii commented on thesis-de/content-de.tex
> +Auf der Weboberfläche werden dem User oder dem Administrator einzelne Graphen,
--ISBN: -- 978-3-89842-839-2

2016-11-23 20:23 UTC, Marcellii commented on thesis-de/content-de.tex
> +Auf der Weboberfläche werden dem User oder dem Administrator einzelne Graphen,
naja oke stellen wir das erstmal nachranging bis ich das Buch gelesen habe :D

2016-11-24 14:17 UTC, bastelfreak commented on thesis-de/content-de.tex
> +einem Koordinaten System angelegt sind. Mit Hilfe von zwei Knoten (x/y) werden
(x/y) -> (bestehend aus jeweils einer X und Y Koordinate) ?

2016-11-24 14:17 UTC, bastelfreak commented on thesis-de/content-de.tex
> +visualiesiert, wenn zwei Knoten miteinander verbunden werden.
visualisiert

2016-11-24 14:19 UTC, Marcellii commented on thesis-de/content-de.tex
> +visualiesiert, wenn zwei Knoten miteinander verbunden werden.
done

2016-11-24 14:32 UTC, bastelfreak approved these changes

2016-11-24 14:33 UTC, merged