Workday 26 11
DCC-org/documents pull request #93
Opened 2016-11-26 13:34 UTC by StoneCat

Rewrite Section "Hadoop / Hive / Impala"
Add description to Hive
Add description to Impala

2016-11-26 14:26 UTC, bastelfreak requested changes

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
>  Data Node's in der Datenhaltungslandschaft eingesetzt werden, so mehr Data
kein apostroph

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
>  Data Node's in der Datenhaltungslandschaft eingesetzt werden, so mehr Data
so mehr -> je mehr

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Node's, umso mehr Speicherplatz und Rechenleistung steht zur Verfügung. Nummer
keine apostroph

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
> +besitzt diese Hadoop-Komponente einen Data Node, welcher aus reinem
aus arbeitsspeicher besteht? Du meinst die komponente läuft komplett im Ram?

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
>  Erfüllung von verschiedene und spezialisierten Aufgaben, werden unter dem
verschiedene -> verschiedenen

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Hive mehrere Sichten auf einene einzelnen Datensatz definieren und somit auch
einene -> einen

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
> +dem Data Warehouse bekannten ``Data Marts'' fallen somit weg und werden durch
wurde Data Marts zuvor irgendwo erklärt? Sollte wohl ins glossar

2016-11-26 14:26 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Verknüpfung  (Interface) von einem Strukturmodell. In den meisten Fällen
ein leerzeichen zu viel nach Veknüpfung

2016-11-26 14:41 UTC, StoneCat commented on thesis-de/content-de.tex
> +dem Data Warehouse bekannten ``Data Marts'' fallen somit weg und werden durch
Kommt noch in einem anderem Pull

2016-11-26 15:17 UTC, bastelfreak approved these changes

2016-11-28 20:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +letzte Aufgabe erfüllt der Backup Node, auch bei diesem handelt es sich um ein
eventuelle "das" Backup Node

2016-11-28 20:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +wiederrum die Aufgaben im mehreren Threads abarbeiten können. Gleichzeitig
der Satz "wiederrum die Aufgaben im mehreren Threads abarbeiten" klingt komisch also das "im" darin

2016-11-28 20:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +Information in Falle einer erneuten Abfrage innerhalb dieser Zeit erneut
anstatt "in" -> "im"

2016-11-28 20:56 UTC, StoneCat commented on thesis-de/content-de.tex
> +letzte Aufgabe erfüllt der Backup Node, auch bei diesem handelt es sich um ein
Nope

2016-11-28 21:01 UTC, merged