Add section Interface
DCC-org/documents pull request #98
Opened 2016-11-30 15:54 UTC by Marcellii

I have created the Section Interface for the Frontend, please only do a
proof reading, because i will only know if this is ok.

2016-12-01 12:23 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Authentifiziert werden kann.
leerzeile einfügen, kürzel einbauen

2016-12-01 12:23 UTC, bastelfreak commented on thesis-de/content-de.tex
> +Die Weboberfläche besitzt zwei Schnittstellen, welche aufgeteilt sind, mit der
satz ist etwas lang

2016-12-01 14:03 UTC, Marcellii commented on thesis-de/content-de.tex
> +Die Weboberfläche besitzt zwei Schnittstellen, welche aufgeteilt sind, mit der
würde ich so lassen wollen erstmal

2016-12-01 14:03 UTC, Marcellii commented on thesis-de/content-de.tex
> +Authentifiziert werden kann.
hab ich eingefügt

2016-12-05 18:42 UTC, StoneCat approved these changes

2016-12-05 18:42 UTC, StoneCat commented on thesis-de/content-de.tex
> +Die erste Schnittstelle der Weboberfläche hat nur eine lesende Berechtigung,
Die erste Schnittstelle der Weboberfläche ist ein standartisierter Treiber, welchen man verwenden kann um auf ein Datenhaltungssystem zuzugreifen. Dieser liefert der Weboberfläche alle nötigen Funktionen und Werkzeuge zur Datenextraktion, Datenmanipulation und der Rechteverwaltung auf einem Datenhaltungssystem. In der Ziellösung von diesem Projekt ist eine rein lesender Datenhaltungszugriff für die Weboberfläche vorgesehen. Dies wird von dem Datenhaltungssystem-Administrator gewährleistet.

2016-12-05 18:42 UTC, StoneCat commented on thesis-de/content-de.tex
> +durchgeführt werden muss. Die Schnittstelle zwischen den Datenhaltungssystemen
[Neuer Absatz]
Neben der Verwendung eines Treibers in Verbindung mit einem Berechtigungskonzept, kann auch ein API-System zum Einsatz kommen. Die Vorteile, sowie die Rolle dieses Systems innerhalb dieses Projektes kann aus Punkt~\ref{subsec:schnittstelle_datenbereitstellung} entnommen werden.

2016-12-05 18:42 UTC, StoneCat commented on thesis-de/content-de.tex
> +Die zweite Schnittstelle ist die Ausgabe der durch die Datenhaltungssystem
Singular von Datenhaltungssystem

2016-12-05 18:42 UTC, StoneCat commented on thesis-de/content-de.tex
> +realisiert. Dies dient zum einem für die Verschlüsselung der Verbindung von
Hier mehr Text zu: Das das geil ist, weil der Mensch nun vorher unstrukturierte Daten bla bla in einem Graphen/Weboberfläche/Anzeige auf einem Blick, schnell und vollstänig bla bla sehen und lesen und interpretieren bla bla kann und zum schluss bei bedarf auch exportieren und das Abbild festhalten kann bla bla

2016-12-06 19:57 UTC, Marcellii commented on thesis-de/content-de.tex
> +Die erste Schnittstelle der Weboberfläche hat nur eine lesende Berechtigung,
angepasst

2016-12-06 20:00 UTC, Marcellii commented on thesis-de/content-de.tex
> +durchgeführt werden muss. Die Schnittstelle zwischen den Datenhaltungssystemen
hab ich angepasst

2016-12-06 20:00 UTC, Marcellii commented on thesis-de/content-de.tex
> +Die zweite Schnittstelle ist die Ausgabe der durch die Datenhaltungssystem
hinfällig

2016-12-10 11:47 UTC, StoneCat approved these changes
Zwei Anmerkungen noch :-)

2016-12-10 11:47 UTC, StoneCat commented on thesis-de/content-de.tex
> +dem Datenhaltungssystem- Administrator gewährleistet.
Leerzeichen zweischen "Datenhaltungssystem- Administrator" weg

2016-12-10 11:47 UTC, StoneCat commented on thesis-de/content-de.tex
> +exportiert und als Abbild festgehalten werden, um hiermit weitere Analysen
nicht um weitere analysen durchzuführen, ich würde eher sagen um diese an Personen zu reporten, welchen keinen direkten Zugriff auf das System haben. Als Beispiel der Geschäftsführer weil der kein Bock hat sich einzuloggen / seinen Account zu verwalten.

2016-12-10 19:58 UTC, Marcellii commented on thesis-de/content-de.tex
> +dem Datenhaltungssystem- Administrator gewährleistet.
hab

2016-12-12 19:12 UTC, StoneCat requested changes

2016-12-12 19:12 UTC, StoneCat commented on thesis-de/content-de.tex
> +Zugriff auf das System besitzen, Anylsen oder Statistiken durchführen.
Anylsen -> Analysen

2016-12-12 19:16 UTC, StoneCat requested changes

2016-12-12 19:16 UTC, StoneCat commented on thesis-de/content-de.tex
> +
Remove this

2016-12-14 11:44 UTC, Marcellii commented on thesis-de/content-de.tex
> +Zugriff auf das System besitzen, Anylsen oder Statistiken durchführen.
done

2016-12-14 11:47 UTC, Marcellii commented on thesis-de/content-de.tex
> +
done

2016-12-17 16:01 UTC, StoneCat approved these changes

2016-12-17 16:01 UTC, merged