Create userstorys for my section
DCC-org/documents pull request #99
Opened 2016-12-01 11:37 UTC by Marcellii

i have created the user storys for my section

2016-12-01 11:52 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\end{outline}
kürzel fehlt

2016-12-01 13:56 UTC, Marcellii commented on thesis-de/content-de.tex
> +\end{outline}
done

2016-12-01 13:58 UTC, bastelfreak commented on thesis-de/content-de.tex
> +\end{outline}
bitte tauschen, erst das kürzel, dann die leerzeile

2016-12-04 15:52 UTC, Marcellii commented on thesis-de/content-de.tex
> +\end{outline}
oke habe ich angepasst

2016-12-05 18:44 UTC, StoneCat requested changes

2016-12-05 18:44 UTC, StoneCat commented on thesis-de/content-de.tex
> +Visualisierte Ausgabe in Form von Graphen zu erhalten. Diese sollen Aufschluss
visualisierte -> klein -> die Ausgabe

2016-12-05 18:46 UTC, Marcellii commented on thesis-de/content-de.tex
> +Visualisierte Ausgabe in Form von Graphen zu erhalten. Diese sollen Aufschluss
done

2016-12-10 11:41 UTC, StoneCat approved these changes

2016-12-10 11:41 UTC, merged